- name: copy iotapm nginx config
  template:
    src: ../shared-files/iotapm.conf.j2
    dest: /etc/nginx/conf.d/iotapm.conf
    validate: "/usr/local/bin/validate_nginx_config.sh -t %s -d iotapm.conf"
  notify:
    - reload nginx

- name: copy grafana nginx config
  template:
    src: ../shared-files/grafana.conf.j2
    dest: /etc/nginx/conf.d/grafana.conf
    validate: "/usr/local/bin/validate_nginx_config.sh -t %s -d grafana.conf"
  notify:
    - reload nginx

- name: copy prometheus nginx config
  template:
    src: ../shared-files/prometheus.conf.j2
    dest: /etc/nginx/conf.d/prometheus.conf
    validate: "/usr/local/bin/validate_nginx_config.sh -t %s -d prometheus.conf"
  notify:
    - reload nginx

- name: copy alertmanager nginx config
  template:
    src: ../shared-files/alertmanager.conf.j2
    dest: /etc/nginx/conf.d/alertmanager.conf
    validate: "/usr/local/bin/validate_nginx_config.sh -t %s -d alertmanager.conf"
  notify:
    - reload nginx
