- name: copy certbot haproxy script
  copy:
    src: files/certbot-haproxy.sh
    dest: /usr/local/bin/certbot-haproxy.sh
    mode: 0755
  tags:
    - certbot
    - scripts

- name: 'download certbot images, this can take a moment...'
  docker_image:
    name: "{{ certbot_image }}"
    tag: "{{ certbot_tag }}"
    force_source: "{{ force_pull_image | default('no') }}"
    source: pull
  tags:
    - certbot_docker_image
  register: download_image_status
  until: download_image_status is succeeded
  retries: 2
  delay: 5
