- name: allow remote lb ports in firewall
  ufw:
    rule: allow
    direction: in
    proto: tcp
    port: "{{ item }}"
  with_items:
    - "{{ iri_api_port_remote }}"
    - "{{ haproxy_stats_port }}"

- name: rate limit iri api port in firewall
  ufw:
    rule: limit
    direction: in
    proto: tcp
    port: "{{ iri_api_port_remote }}"
    log: yes
  when: ufw_limit_iri_api is defined and ufw_limit_iri_api
