- name: restart iota-pm
  systemd:
    name: iota-pm.service
    state: restarted
    daemon_reload: yes
    enabled: yes
  when: not iotapm_started.changed

- name: reload systemd
  command: systemctl daemon-reload
