#!/bin/bash
set -o pipefail

# This is just a proof-of-concept. Use with care.
# Only use if you installed your node using iri-playbook

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root"
   echo "Please change to root: 'sudo su -' and re-run"
   exit 1
fi

clear
[ -f "$HOME/.iric" ] && . "$HOME/.iric"
EDITOR="${EDITOR:-nano}"
VERSION=0.3.3
CUR_DIR=$(pwd)
WIDTH=78
export NEWT_COLORS='
window=,
'

function pause(){
   read -p "$*"
   clear
}

function cleanup() {
    cd "$CUR_DIR"
    clear
}

trap cleanup INT TERM EXIT

# Experimental Admin settings
function set_admin_user() {
    USER_CHOICE=$(whiptail --inputbox "Pick a name for the administrator account:" 8 $WIDTH ${ADMIN_USER} --title "Username (allowed regex: a-zA-Z0-9_)" 3>&1 1>&2 2>&3)
    RC=$?
    if [[ $RC -eq 0 ]]; then
        echo -n "${USER_CHOICE}"
    else
        echo -n "${ADMIN_USER}"
    fi
}

function get_admin_user() {
    ADMIN_USER=$(set_admin_user)
    if [[ "$ADMIN_USER" =~ [^a-zA-Z0-9_] ]]; then
        whiptail --title "Invalid Username!" \
                 --msgbox "Username can only contain alphanumeric characters and underscores." \
                 8 $WIDTH
        get_admin_user
    fi
}

function set_admin_password_a() {
    whiptail --passwordbox "please enter your secret password" 8 $WIDTH --title "password dialog" 3>&1 1>&2 2>&3
}

function set_admin_password_b() {
    whiptail --passwordbox "please repeat" 8 $WIDTH --title "password dialog" 3>&1 1>&2 2>&3
}

function get_admin_password() {
    PASSWORD_A=$(set_admin_password_a)
    PASSWORD_B=$(set_admin_password_b)

    if [ "$PASSWORD_A" != "$PASSWORD_B" ]; then
        whiptail --title "Passwords Mismatch!" \
                 --msgbox "Passwords do not match, please try again." \
                 8 $WIDTH
        get_admin_password
    fi

    PASSWD_CHECK=$(echo -n "$PASSWORD_A" | cracklib-check)
    if [[ $(echo "$PASSWD_CHECK" | awk {'print $2'}) != "OK" ]]; then
        whiptail --title "Weak Password!" \
                 --msgbox "Please choose a better password:$(echo ${PASSWD_CHECK}|cut -d: -f2-)" \
                 8 $WIDTH
        get_admin_password
    fi
    ADMIN_PASSWORD="${PASSWORD_A}"
}

### Playbook ###
function verify_playbook() {
    local OUTPUT
    local HEIGHT
    local RC
    if [ ! -d /opt/iri-playbook ]; then
        whiptail --title "Missing Playbook!" \
                 --msgbox "ERROR: Cannot find the iri-playbook in /opt/iri-playbook!" \
                 8 $WIDTH
        return 1
    fi
    cd /opt/iri-playbook
    OUTPUT=$(git pull 2>&1)
    RC=$?
    HEIGHT=$(expr $(echo "$OUTPUT"|wc -l) + 10)
    if [[ $RC -ne 0 ]]; then
        whiptail --title "Git Errors" \
                 --msgbox "Errors when trying to update the playbook repository: $OUTPUT" \
                 $HEIGHT $WIDTH
        return 1
    fi
}

### Field ###
function enable_field() {
    local NODE_NAME="playbook_$(tr -cd '[:alnum:]' < /dev/urandom | fold -w10 | head -n1)"
    NODE_NAME=$(whiptail --inputbox "Choose a unique node name:" 8 $WIDTH "$NODE_NAME" --title "Choose Node Name" 3>&1 1>&2 2>&3)
    if [[ $? -ne 0 ]] || [[ "$NODE_NAME" == "" ]]; then
        return
    elif [[ "$NODE_NAME" =~ [^a-zA-Z0-9_] ]]; then
        whiptail --title "Invalid Input" \
                 --msgbox "Invalid input provided. Only alphanumeric values are allowed and underscore." \
                  8 $WIDTH
        return 1
    fi

    local ADDRESS_ARG="-e field_address="
    local ADDRESS=$(whiptail --inputbox "Enter payout address or leave blank to configure manually later on:" \
                    8 $WIDTH --title "Choose Address" 3>&1 1>&2 2>&3)
        
    if [[ $? -ne 0 ]]; then
        return
    elif [[ "$ADDRESS" == "" ]]; then
        ADDRESS_ARG=""
    elif [[ "$ADDRESS" =~ [^A-Z9] ]] || [[ "${#ADDRESS}" -ne 90 ]]; then
        whiptail --title "Invalid Input" \
                 --msgbox "Invalid IOTA address. Can only use letters A-Z and/or 9. Length should be 90 characters." \
                 8 $WIDTH
        return 1
    else
        ADDRESS_ARG="${ADDRESS_ARG}${ADDRESS}"
    fi

    # Check if id file already exist, and ask if to keep
    local ID_MOVE
    if [ -f "/var/lib/field/.carriota-field.id" ]; then
        if ! (whiptail --title "Field Node ID" \
                     --yesno "An existing node ID file was found in '/var/lib/field/.carriota-field.id'.\n\nDo you want to keep using this one or let Field generate a new one? (choose 'yes' to keep it!)" \
                         12 $WIDTH) then
            ID_MOVE="$(date +%s)"
        fi
    fi

    local ADDRESS_CHOICE
    if [[ "$ADDRESS" == "" ]]; then
        ADDRESS_CHOICE="You chose to enter a payout address later on.\n"
    else
        ADDRESS_CHOICE="You chose this address for payouts: ${ADDRESS}.\n"
    fi

    local ID_CHOICE
    if [[ -n "$ID_MOVE" ]]; then
        ID_CHOICE="An existing Field node ID file will be backed up to /var/lib/field/.carriota-field.id.${ID_MOVE} allowing Field to generate a new one.\n"
    fi

    if (whiptail --title "Enable Field" \
                 --yesno "Please verify the details:\n\nYou chose the node name '${NODE_NAME}'.\n${ADDRESS_CHOICE}\n${ID_CHOICE}\nAre you sure you want to enable Field?" \
                 15 $WIDTH) then

        #verify_playbook
        #if [[ $? -ne 0 ]]; then
        #     whiptail --title "Error!" \
        #              --msgbox "ERROR: Cannot enable Field." \
        #              8 $WIDTH
        #     return 1
        #fi

        # backup old ID file
        [[ -n "$ID_MOVE" ]] && mv "/var/lib/field/.carriota-field.id" "/var/lib/field/.carriota-field.id.${ID_MOVE}"

        # run playbook enabling field
        cd /opt/iri-playbook && ansible-playbook -i inventory -v site.yml --tags=prometheus_config_file,field_exporter,field_role -e "field_enabled=true" -e "my_field_name=$NODE_NAME" $ADDRESS_ARG

        [[ $? -ne 0 ]] && MSG="Enabling Field failed!!! Check output above for errors." || MSG="Installation finished successfully!"
        pause "$MSG Press any key to return to menu."
    fi
}

function get_latest_field_release {
    curl -H 'Cache-Control: no-cache' -s -m 5 -f https://api.github.com/repos/SemkoDev/field.cli/releases/latest | awk '/tag_name/{print $2}' | tr -d '"v,' | cut -d- -f1
}

function upgrade_field() {
    local RC
    local FIELD_VERSION

    echo "Checking for updates..."
    local FIELD_LATEST=$(get_latest_field_release)
    if [[ $? -ne 0 ]]; then
        FIELD_LATEST=unknown
    fi
    clear

    FIELD_VERSION=$(field --version 2>&1)
    if [[ $? -ne 0 ]]; then
        whiptail --title "Error!" \
                 --msgbox "ERROR: Is Field installed?\n$FIELD_VERSION" \
                 10 $WIDTH
        return 1
    fi

    if (( $(awk 'BEGIN {print ("'$FIELD_VERSION'" >= "'$FIELD_LATEST'")}') )); then
        whiptail --title "No Updates" \
                 --msgbox "You already have the latest version: $FIELD_VERSION" \
                 8 $WIDTH
        return
    fi

    if (whiptail --title "Upgrade Field" \
                 --yesno "Are you sure you want to upgrade Field from ${FIELD_VERSION} to ${FIELD_LATEST}?" \
                 8 $WIDTH) then
        #verify_playbook
        #if [[ $? -ne 0 ]]; then
        #     whiptail --title "Error!" \
        #              --msgbox "ERROR: Cannot update Field." \
        #              8 $WIDTH
        #     return 1
        #fi
        cd /opt/iri-playbook && ansible-playbook -i inventory -v site.yml --tags=prometheus_config_file,field_exporter,field_role -e "upgrade_field=true" -e "field_enabled=true"
        [[ $? -ne 0 ]] && MSG="Updating Field failed!!! Check output above for errors." || MSG="Update finished successfully!"
        pause "$MSG Press any key to return to menu."
    fi
}

### Nelson ###
function enable_nelson() {
    local RC
    if (whiptail --title "Enable Nelson" \
                 --yesno "Are you sure you want to enable Nelson automatic peering?" \
                 --defaultno \
                 8 $WIDTH) then
        verify_playbook
        if [[ $? -ne 0 ]]; then
             whiptail --title "Error!" \
                      --msgbox "ERROR: Cannot enable Nelson." \
                      8 $WIDTH
             return 1
        fi
        cd /opt/iri-playbook && ansible-playbook -i inventory -v site.yml --tags=nelson_role -e "nelson_enabled=true"
        [[ $? -ne 0 ]] && MSG="Enabling Nelson failed!!! Check output above for errors." || MSG="Installation finished successfully!"
        pause "$MSG Press any key to return to menu."
    fi
}

function get_latest_nelson_release {
    curl -H 'Cache-Control: no-cache' -s -m 5 -f https://api.github.com/repos/SemkoDev/nelson.cli/releases/latest | awk '/tag_name/{print $2}' | tr -d '"v,' | cut -d- -f1
}

function upgrade_nelson() {
    local RC
    local NELSON_VERSION

    echo "Checking for updates..."
    local NELSON_LATEST=$(get_latest_nelson_release)
    if [[ $? -ne 0 ]]; then
        NELSON_LATEST=unknown
    fi
    clear

    NELSON_VERSION=$(nelson --version 2>&1)
    if [[ $? -ne 0 ]]; then
        whiptail --title "Error!" \
                 --msgbox "ERROR: Is Nelson installed?\n$NELSON_VERSION" \
                 10 $WIDTH
        return 1
    fi

    if (( $(awk 'BEGIN {print ("'$NELSON_VERSION'" >= "'$NELSON_LATEST'")}') )); then
        whiptail --title "No Updates" \
                 --msgbox "You already have the latest version: $NELSON_VERSION" \
                 8 $WIDTH
        return
    fi

    if (whiptail --title "Upgrade Nelson" \
                 --yesno "Are you sure you want to upgrade Nelson from ${NELSON_VERSION} to ${NELSON_LATEST}?" \
                 --defaultno \
                 8 $WIDTH) then
        verify_playbook
        if [[ $? -ne 0 ]]; then
             whiptail --title "Error!" \
                      --msgbox "ERROR: Cannot update Nelson." \
                      8 $WIDTH
             return 1
        fi
        cd /opt/iri-playbook && ansible-playbook -i inventory -v site.yml --tags=nelson_role -e "upgrade_nelson=true" -e "nelson_enabled=true"
        [[ $? -ne 0 ]] && MSG="Updating Nelson failed!!! Check output above for errors." || MSG="Update finished successfully!"
        pause "$MSG Press any key to return to menu."
    fi
}

### IRI ###
function get_latest_iri_release {
    curl -H 'Cache-Control: no-cache' -s -m 5 -f https://api.github.com/repos/iotaledger/iri/releases/latest  | awk '/tag_name/{print $2}' | tr -d '"v,'
}

function upgrade_iri() {
    local RC
    echo "Checking for updates..."
    local IRI_LATEST=$(get_latest_iri_release)
    if [[ $? -ne 0 ]]; then
        whiptail --title "Error!" \
                 --msgbox "ERROR: Failed to get IRI latest version\n${IRI_LATEST}" \
                 8 $WIDTH
        return 1
    fi
    clear
    local IRI_VERSION=$(grep ^api_version $HOME/.nbctl | cut -d: -f2- | sed 's/ *//g')
    if [[ $? -ne 0 ]]; then
        whiptail --title "Error!" \
                 --msgbox "ERROR: Cannot find $HOME/.nbctl" \
                 8 $WIDTH
        return 1
    fi
    
    if (( $(awk 'BEGIN {print ("'$IRI_VERSION'" >= "'$IRI_LATEST'")}') )); then
        if ! (whiptail --title "No Updates" \
                 --yesno "You already have the latest version: ${IRI_VERSION}.\nDo you want to proceed anyway? (will re-download)" \
                 --defaultno \
                 10 $WIDTH) then
            return
        else
            local NO_CONFIRM=1
        fi
    fi

    if [ -z "$NO_CONFIRM" ]; then
        if ! (whiptail --title "Upgrade IRI" \
                     --yesno "Are you sure you want to upgrade IRI from ${IRI_VERSION} to ${IRI_LATEST}?\nWARNING: only do this if you know what your are doing!" \
                     --defaultno \
                     8 $WIDTH) then
            return
        fi
    fi

    verify_playbook
    if [[ $RC -ne 0 ]]; then
        whiptail --title "Error!" \
                 --msgbox "ERROR: Cannot upgrade IRI." \
                 8 $WIDTH
        return 1
    fi
    echo "Downloading new version..."
    IRIVER=${IRI_LATEST}
    TFILE=$(mktemp /tmp/iri-${IRIVER}.XXXXXXXXX)
    wget "https://github.com/iotaledger/iri/releases/download/v${IRIVER}/iri-${IRIVER}.jar" -O "$TFILE"
    if [[ $? -ne 0 ]]; then
         whiptail --title "Error!" \
                  --msgbox "ERROR: Failed upgrading IRI." \
                  8 $WIDTH
         rm -f "$TFILE"
         return 1
    fi
    echo "Move '$TFILE' to '/var/lib/iri/target/iri-${IRIVER}.jar' ..."
    mv "$TFILE" "/var/lib/iri/target/iri-${IRIVER}.jar" && chmod 644 "/var/lib/iri/target/iri-${IRIVER}.jar"
    echo "Update iri configuration files..."
    IRI_CONFIG=$(grep ^file /root/.nbctl | cut -d: -f2)
    sed -i "s/^IRI_VERSION=.*$/IRI_VERSION=$IRI_LATEST/" $IRI_CONFIG
    sed -i "s/^api_version.*$/api_version: $IRI_LATEST/" $HOME/.nbctl
    echo "Restart IRI, this can take a few moments..."
    systemctl restart iri
    pause "Update finished successfully. Nevertheless, it is recommended to check the status of IRI. Press any key to return to menu."
    clear
}

### Monitoring ###
function upgrade_monitoring() {
    local RC
    if (whiptail --title "Upgrade Monitoring" \
                 --yesno "Are you sure you want to upgrade monitoring services?" \
                 --defaultno \
                 8 $WIDTH) then
        verify_playbook
        if [[ $? -ne 0 ]]; then
             whiptail --title "Error!" \
                      --msgbox "ERROR: Cannot upgrade monitoring." \
                      8 $WIDTH
             return 1
        fi

        # Enable ZMQ
        grep -q ^ZMQ_ENABLED /var/lib/iri/iri.ini || echo "ZMQ_ENABLED = true" >>/var/lib/iri/iri.ini && systemctl restart iri

        # Upgrade iota-prom-exporter and dashboards
        cd /opt/iri-playbook && ansible-playbook -i inventory -v site.yml --tags=iri_ssl,prometheus_config,monitoring_deps,iota_prom_exporter,grafana_config -e overwrite=yes
        [[ $? -ne 0 ]] && MSG="Updating monitoring failed!!! Check output above for errors." || MSG="Update finished successfully!"
        pause "$MSG Press any key to return to menu."
        clear
    fi
}


### Haproxy ###
function enable_haproxy() {
    local RC
    local DEFAULT_MSG="Are you sure you want to enable wallet access only via HAProxy?\nThis will disable port 14265 externally and make 14267 accessible.\nIn addition, all the REMOTE_LIMIT_API commands will be under control of HAProxy and no longer via IRI configuration files."
    [ -n "$1" ] && { DEFAULT_MSG=$1; }
    if (whiptail --title "HAProxy" \
                 --yesno "$DEFAULT_MSG" \
                 --defaultno \
                 8 $WIDTH) then
        verify_playbook
        if [[ $? -ne 0 ]]; then
             whiptail --title "Error!" \
                      --msgbox "ERROR: haproxy task failed." \
                      8 $WIDTH
             return 1
        fi

        cd /opt/iri-playbook && ansible-playbook -i inventory -v site.yml --tags=iri_ssl,loadbalancer_role -e lb_bind_address=0.0.0.0 -e overwrite=yes
        [[ $? -ne 0 ]] && MSG="Enabling HAProxy failed!!! Check output above for errors." || MSG="Installation finished successfully!"
        pause "$MSG Press any key to return to menu."
    fi
}



### Notice ###
function how_to_setup() {
    whiptail --title "IRIC v${VERSION} - Instructions" \
             --msgbox "Check that you have the .nbctl file in your home folder (ls -l ~/.nbctl).\nExample of the file's contents:\n\napi_version: 1.4.2.2\nhost: http://127.0.0.1:14265\nfile: /etc/default/iri\n\nThis will allow this script to use the nbctl utility to manage neighbors and get the node's data." \
             15 $WIDTH
}


### Neighbors ###
function add_neighbors() {
    local NEIGHBORS
    local HEIGHT
    local NBCTL_OUTPUT
    local RC
    local IRI_CONFIG

    NEIGHBORS=$(whiptail --inputbox "Enter a list of neighbors separated by space:" 8 $WIDTH --title "Add Neighbors" 3>&1 1>&2 2>&3)
    RC=$?
    if [[ $RC -ne 0 ]]; then
        return
    fi

    ADD_LIST=$(echo "$NEIGHBORS" | sed 's/  */ /g' | sed 's/ / -n /g' | sed 's/^\(.*\)/-n \1/')
    if ! (echo "$ADD_LIST" | egrep -q "tcp|udp"); then
        whiptail --title "Invalid Input" \
                 --msgbox "Invalid input provided. Please check the syntax you provided is valid." \
                  8 $WIDTH
        return
    fi

    HEIGHT=$(expr $(echo "$NEIGHBORS"|wc -l) + 8)
    if (whiptail --title "Add Neighbors" \
                 --yesno "The following neighbor(s) will be added:\n\n $NEIGHBORS" \
                 $HEIGHT $WIDTH) then
        IRI_CONFIG=$(grep ^file /root/.nbctl | cut -d: -f2)
        [ -n "$IRI_CONFIG" ] && IRI_CONFIG="-f $IRI_CONFIG"
        NBCTL_OUTPUT=$(nbctl -a $ADD_LIST $IRI_CONFIG 2>&1)
        RC=$?
        if [[ $RC -eq 0 ]]; then
            HEIGHT=$(expr $(echo "$NBCTL_OUTPUT"|wc -l) + 7)
            whiptail --title "Added Neighbors" \
                     --msgbox "$NBCTL_OUTPUT" \
                    $HEIGHT $WIDTH
        else
            if echo "$NBCTL_OUTPUT" | grep -q "urllib2.URLError" ; then
               NBCTL_OUTPUT="Failed to communicate with IRI API port. Check if IRI is active and if $HOME/.nbctl is configured correctly."
            fi
            HEIGHT=$(expr $(echo "$NBCTL_OUTPUT"|wc -l) + 10)
            whiptail --title "Adding Neighbors Failed" \
                     --msgbox "Failure: $NBCTL_OUTPUT" \
                     $HEIGHT $WIDTH
        fi
    fi
}

function remove_neighbors() {
    local NEIGHBORS_ARRAY
    local NEIGHBORS
    local NEIGHBOR
    local HEIGHT
    local IRI_CONFIG

    echo "Getting neighbors list..."
    NEIGHBORS=$(list_neighbors get)
    RC=$?
    clear
    if [[ $RC -ne 0 ]]; then
        whiptail --title "Neighbors Failed" \
                 --msgbox "Failed to get list of neighbors: $NEIGHBORS" \
                 8 $WIDTH
        return
    fi
    if [ "$NEIGHBORS" == "" ]; then
        whiptail --title "No Neighbors" \
                 --msgbox "There are no neighbors configured" \
                 8 $WIDTH
        return
    fi
    HEIGHT=$(expr $(echo "$NEIGHBORS"|wc -l) + 5)
    NEIGHBORS_ARRAY=($(echo "$NEIGHBORS"))
    NEIGHBORS_ARRAY_INDEXED=($(echo "$NEIGHBORS"| awk '!/^ / && NF { print NR")"; print $1}'))
    NEIGHBOR_INDEX=$(whiptail --title "Remove neighbors" --menu "Choose a neighbor" 25 $WIDTH 16  "${NEIGHBORS_ARRAY_INDEXED[@]}" 3>&1 1>&2 2>&3)
    if [ $? -eq 1 ]; then
        return
    fi

    NEIGHBOR_INX=$(echo "$NEIGHBOR_INDEX" | cut -d')' -f1)
    NEIGHBOR_INX=$(expr $NEIGHBOR_INX - 1)
    TO_REMOVE="${NEIGHBORS_ARRAY[$NEIGHBOR_INX]}"
    SCHEME=$(echo "$TO_REMOVE"|cut -d'/' -f2)
    ADDRESS=$(echo "$TO_REMOVE"|cut -d'/' -f1)
    if (whiptail --title "Confirm removal" \
                 --yesno "Are you sure you want to remove: ${SCHEME}://${ADDRESS}" \
                 --defaultno \
                 8 $WIDTH)
    then
        IRI_CONFIG=$(grep ^file /root/.nbctl | cut -d: -f2)
        [ -n "$IRI_CONFIG" ] && IRI_CONFIG="-f $IRI_CONFIG"
        REMOVAL_OUTPUT=$(nbctl -r -n "${SCHEME}://${ADDRESS}" $IRI_CONFIG 2>&1)
        if [ $? -eq 0 ];then
            whiptail --title "Removed successfully" \
                     --msgbox "$REMOVAL_OUTPUT" \
                     12 $WIDTH
        else
            HEIGHT=$(expr $(echo "$REMOVAL_OUTPUT"|wc -l) + 7)
            whiptail --title "Remove failed!" \
                     --msgbox "${REMOVAL_OUTPUT}" \
                     $HEIGHT $WIDTH
        fi
    fi
}

function list_neighbors() {
    local NEIGHBORS_QUERY
    local NEIGHBORS
    local HEIGHT
    local RETURN_RES=$1
    NEIGHBORS_QUERY=$(nbctl -l 2>&1)
    RC=$?
    if [[ $RC -ne 0 ]]; then
        if echo "$NEIGHBORS_QUERY" | egrep -q "urllib2.URLError|timeout|refused" ; then
            NEIGHBORS_QUERY="Failed to communicate with IRI API port. Check if IRI is active and if $HOME/.nbctl is configured correctly."
        else
            NEIGHBORS_QUERY="Unknown error"
        fi
        if [ -n "$RETURN_RES" ]; then
            echo "$NEIGHBORS_QUERY"
            return 1
        fi
        HEIGHT=$(expr $(echo "$NEIGHBORS_QUERY"|wc -l) + 7)
        whiptail --title "List neighbors failed" \
                 --msgbox "$NEIGHBORS_QUERY" \
                 $HEIGHT $WIDTH
        return 1
    else
        NEIGHBORS=$( echo "$NEIGHBORS_QUERY" | jq -r '.neighbors[] | "\(.address)/\(.connectionType)"' )
        if [ -n "$RETURN_RES" ]; then
            echo "$NEIGHBORS"
            return 0
        fi

        if [ "$NEIGHBORS" == "" ]; then
            LENGTH=0
        else
            LENGTH=$(echo "$NEIGHBORS"|wc -l)
        fi
        local HEIGHT=$(expr $LENGTH + 8)
        whiptail --title "List Neighbors" \
                 --msgbox "Total: ${LENGTH} neighbor(s)\n\n${NEIGHBORS}" \
                 $HEIGHT $WIDTH
    fi
}

### Get DB ###
function get_db() {
    XVPS_SOURCE="https://x-vps.com/iota.db.tgz"
    DB_SOURCE=$(whiptail --inputbox "This action will download and boostrap a fully synced database.\nChoose a source where to download the database from:" 8 $WIDTH  $XVPS_SOURCE --title "IRIC v${VERSION} - Download Database" 3>&1 1>&2 2>&3)
    if [[ $? -ne 0 ]]; then
        return
    fi

    if [ "$DB_SOURCE" == "$XVPS_SOURCE" ]; then
        local JSON_OUTPUT=$(curl -H "Content-Type: application/json" -m 4 -f -s https://x-vps.com/index.php 2>/dev/null)
        local FILE_SIZE=$(echo "$JSON_OUTPUT" | jq -r .file_size)
        local LAST_UPDATED=$(echo "$JSON_OUTPUT" | jq -r .last_updated)
    fi
    if (whiptail --title "Confirm DB" \
                 --yesno "Download new database from '$DB_SOURCE'?\n\nupdated: ${LAST_UPDATED}, size: ${FILE_SIZE}" \
                 12 $WIDTH) then
        TFILE=$(mktemp /tmp/iota.db.tgz.XXXXXXXXX)
        cd /tmp && wget -O $TFILE "$DB_SOURCE" && systemctl stop iri && rm -rf /var/lib/iri/target/mainnetdb* && mkdir /var/lib/iri/target/mainnetdb/ && echo "Extracting DB files..." && pv $TFILE | tar xzf - -C /var/lib/iri/target/mainnetdb/ && chown iri.iri /var/lib/iri -R && rm -f $TFILE && systemctl start iri
        if [[ $? -ne 0 ]]; then
            whiptail --title "New DB Failed!" \
                     --msgbox "Well this is embarrassing. Downloading the new DB failed..." \
                     8 $WIDTH
            rm -f $TFILE
            return 1
        else
            pause "Done! Please check IRI's status and logs to verify it is error free."
            clear
        fi
    fi
}

## IRIC
function get_latest_iric_version() {
    local RAND=$(echo -n $(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 7 | head -n 1))
    curl -s -f -m 5 -H 'Cache-Control: no-cache' "https://raw.githubusercontent.com/nuriel77/iri-playbook/master/roles/iri/files/iric?nocache=$RAND"|grep ^VERSION|cut -d= -f2
}

function check_new_iric() {
    local CURR_VERSION=$VERSION
    local IRIC_VERSION=$(get_latest_iric_version 2>&1)
    if [[ $? -ne 0 ]] || [[ "$IRIC_VERSION" == "" ]]; then
        return 1
    fi

    if (( $(awk 'BEGIN {print ("'$CURR_VERSION'" >= "'$IRIC_VERSION'")}') )); then
        return 1
    else
        return 0
    fi
}

function update_iric() {
    local IRIC_VERSION=$(get_latest_iric_version 2>&1)
    local CURR_VERSION=$VERSION
    if [[ $? -ne 0 ]] || [[ "$IRIC_VERSION" == "" ]]; then
        whiptail --title "IRIC Update Failed" \
                 --msgbox "Failed to get IRIC version from github." \
                 8 $WIDTH
        return 1
    fi

    if (( $(awk 'BEGIN {print ("'$CURR_VERSION'" >= "'$IRIC_VERSION'")}') )); then
        whiptail --title "No Updates" \
                 --msgbox "You already have the latest version: $VERSION." \
                 8 $WIDTH
        return
    fi

    if (whiptail --title "Confirm Update" \
                 --yesno "Are you sure you want to update IRIC from '$VERSION' to '$IRIC_VERSION'?" \
                 8 $WIDTH) then
        verify_playbook
        if [[ $? -ne 0 ]]; then
             whiptail --title "Error!" \
                      --msgbox "ERROR: playbook task failed." \
                      8 $WIDTH
             return 1
        fi
        cd /opt/iri-playbook && ansible-playbook -i inventory site.yml -v --tags=scripts,nbctl_config
        [[ $? -ne 0 ]] && MSG="Updating IRIC failed!!! Check output above for errors." || MSG="Update finished successfully!"
        pause "$MSG Press any key to return to menu."
        clear
        exec "$0"
    fi
}

### Configs ###
function choose_editor() {
    USER_CHOICE=$(whiptail --inputbox "Choose a default text editor:" 8 $WIDTH ${EDITOR} --title "Choose Editor" 3>&1 1>&2 2>&3)
    if [[ $? -ne 0 ]]; then
        return
    fi

    which $USER_CHOICE >/dev/null 2>&1
    if [[ $? -ne 0 ]]; then
        whiptail --title "Error!" \
                 --msgbox "ERROR: Invalid editor or editor not found on system." \
                 8 $WIDTH
        return 1
    fi

    EDITOR=$USER_CHOICE
    if ! grep -q "^export EDITOR" $HOME/.iric; then
        echo "export EDITOR=${EDITOR}" >> $HOME/.iric
    else
        sed -i "s/^export EDITOR=.*/export EDITOR=${EDITOR}/g" $HOME/.iric
    fi
}

function edit_config_file() {
    local CONFIG=$1
    local SERVICE=$2

    BEFORE_EDIT=$(md5sum $CONFIG | awk {'print $1'})
    $EDITOR ${CONFIG}
    AFTER_EDIT=$(md5sum $CONFIG | awk {'print $1'})

    if [[ "$AFTER_EDIT" != "$BEFORE_EDIT" ]]; then
        if (whiptail --title "File Modified" \
                     --yesno "${CONFIG} file was modified.\n${SERVICE} requires a restart to pick up the new changes.\nDo you want to restart it now?" \
                     8 $WIDTH) then
            service_cmd $SERVICE restart
        fi
    fi
}

function edit_config() {
    local CONFIG_FILE=$1
    local SERVICE=$2
    if [ ! -f $CONFIG_FILE ]; then
        whiptail --title "Missing File" \
                 --msgbox "Error: cannot find '$CONFIG_FILE'" \
                 8 $WIDTH
        return 1
    fi

    # Make backup for restores
    if [ ! -f ${CONFIG_FILE}.original ]; then
        cp ${CONFIG_FILE} ${CONFIG_FILE}.original
    fi

    if edit_config_file ${CONFIG_FILE} ${SERVICE}; then
        return 0
    else
        return 1
    fi
}

### Node info ###
function show_lmsi() {
    if [ ! -f $HOME/.nbctl ]; then
        whiptail --title "Missing .nbctl" \
                 --msgbox "Error: cannot find $HOME/.nbctl" \
                 8 $WIDTH
        return
    fi
    IRI_HOST=$(grep ^host $HOME/.nbctl | cut -d: -f2-)
    local IRI_API_VERSION=$(grep ^api_version $HOME/.nbctl | cut -d: -f2-)
    local LSMI_LOCAL=$(curl -f -m 5 -s $IRI_HOST -X POST -H "X-IOTA-API-Version: $IRI_API_VERSION" -H 'Content-Type: application/json' -d '{"command": "getNodeInfo"}'| python -m json.tool|egrep "latestSolidSubtangleMilestoneIndex|latestMilestoneIndex"| sed 's/,//'|sed -e 's/^[ \t]*//'|sed 's/"//g')
    if [ $? -ne 0 ]; then
        whiptail --title "Query failed" \
                 --msgbox "Error: failed query ${LSMI_LOCAL}. Check if IRI is active and if $HOME/.nbctl is configured properly." \
                 12 $WIDTH
        return
    fi

    local LSMI_QUERY=$(curl -H 'Cache-Control: no-cache' -s -f -m 5 https://x-vps.com/lmsi|jq -r .latestMilestoneIndex 2>/dev/null)
    if [ $? -eq 0 ]; then
        OUTPUT="Latest milestone index: ${LSMI_QUERY}\n\n"
    else
        OUTPUT=""
    fi
    OUTPUT="${OUTPUT}Local:\n\n${LSMI_LOCAL}"
    whiptail --title "LatestMilestoneIndex" \
             --msgbox "$OUTPUT" \
             12 $WIDTH
}

function get_node_info() {
    if [ ! -f $HOME/.nbctl ]; then
        whiptail --title "Missing .nbctl" \
                 --msgbox "Error: cannot find $HOME/.nbctl" \
                 8 $WIDTH
        return
    fi
    local IRI_HOST=$(grep ^host $HOME/.nbctl | cut -d: -f2-)
    local IRI_API_VERSION=$(grep ^api_version $HOME/.nbctl | cut -d: -f2-)
    NODE_INFO=$(curl -f -m 5 -s $IRI_HOST -X POST -H "X-IOTA-API-Version: $IRI_API_VERSION" -H 'Content-Type: application/json' -d '{"command": "getNodeInfo"}'| jq -r 'to_entries[] | "\(.key): \(.value )"' | column -t | sort)
    if [ $? -ne 0 ]; then
        whiptail --title "Query failed" \
                 --msgbox "Error: failed query ${NODE_INFO}. Check if IRI is active and if $HOME/.nbctl is configured properly." \
                 12 $WIDTH
        return
    fi

    HEIGHT=$(expr $(echo "$NODE_INFO"|wc -l) + 7)
    whiptail --title "Node Info" \
             --msgbox "$NODE_INFO" \
             $HEIGHT $WIDTH
}

### PS MEM ###
function view_ps_mem() {
    which ps_mem >/dev/null 2>&1
    if [[ $? -ne 0 ]]; then
         whiptail --title "Missing ps_mem" \
         --msgbox "Error: cannot find 'ps_mem' utility!" \
         8 $WIDTH
         return 1
    fi

    whiptail --title "ps_mem utility" \
             --msgbox "This utility shows a per-process total memory usage.\nUse arrows or page up/down to scroll and q to exit." \
             8 $WIDTH
    ps_mem 2>/dev/null|less
}

### Services ###
function service_status() {
    local SERVICE
    SERVICE=$1
    # Pipe to less as some distros don't use pager
    systemctl status $SERVICE|less
}

function service_cmd() {
    local SERVICE
    local COMMAND
    local OUTPUT
    local EXTRA_CMD
    local DISABLE
    local STATE
    SERVICE=$1
    COMMAND=$2
    EXTRA_CMD=$3

    echo "Running 'systemctl $COMMAND $SERVICE' ..."
    if [ "$EXTRA_CMD" == "disable" ]; then
        systemctl disable $SERVICE
        STATE="and disable"
    elif [ "$EXTRA_CMD" == "enable" ]; then
        systemctl enable $SERVICE
        STATE="enabled"
    fi

    if [ "$EXTRA_CMD" != "enable" ]; then
        OUTPUT=$(systemctl $COMMAND $SERVICE 2>&1)
    else
        OUTPUT=""
    fi
    HEIGHT=$(expr $(echo "$OUTPUT"|wc -l) + 7)
    if [ $? -ne 0 ]; then
        whiptail --title "Failed" \
                 --msgbox "$COMMAND $SERVICE failed: $OUTPUT" \
                 $HEIGHT 48
    else
        whiptail --title "Success" \
                 --msgbox "$COMMAND $SERVICE $STATE OK" \
                 $HEIGHT 48
    fi
    clear
}

function service_log() {
    local SERVICE
    local ARGS
    SERVICE=$1
    # Pipe to less in the case too few lines.
    # This will prevent immediately exiting the view
    journalctl -u $SERVICE|less
}

function service_menu() {
    local SERVICE
    SERVICE=$1
    whiptail --title "IRIC v${VERSION} - $SERVICE Service" \
             --menu "For logs use SHIFT-g to skip to end of log, or q to exit." \
             --cancel-button "Back" \
             25 $WIDTH 16 \
    "a)" "Status" \
    "b)" "Start" \
    "c)" "Stop" \
    "d)" "Restart" \
    "e)" "Disable start on reboot" \
    "f)" "Enable start on reboot" \
    "g)" "View log" \
    3>&1 1>&2 2>&3
}

function service() {
    local SERVICE
    local CHOICE
    SERVICE=$1
    CHOICE=$(service_menu $SERVICE)
    RC=$?
    if [[ $RC -eq 1 ]]; then
        return
    fi
    case "$CHOICE" in

        "a)")
            service_status $SERVICE
            service $SERVICE
            ;;

        "b)")
            service_cmd $SERVICE start
            service $SERVICE
            ;;

        "c)")
            service_cmd $SERVICE stop
            service $SERVICE
            ;;

        "d)")
            service_cmd $SERVICE restart
            service $SERVICE
            ;;

        "e)")
            service_cmd $SERVICE stop disable
            service $SERVICE
            ;;

        "f)")
            service_cmd $SERVICE "" enable
            service $SERVICE
            ;;

        "g)")
            service_log $SERVICE
            service $SERVICE
            ;;

        *)
            service $SERVICE
            ;;
    esac
}

function services_menu() {
    whiptail --title "IRIC v${VERSION} - Node Services" \
             --menu "Choose an option" \
             --cancel-button "Back" \
             25 $WIDTH 16 \
    "a)" "IRI" \
    "b)" "IOTA Peer Manager" \
    "c)" "Prometheus" \
    "d)" "Alert Manager" \
    "e)" "Grafana" \
    "f)" "IOTA Prometheus Exporter" \
    "g)" "Nginx" \
    "h)" "HAProxy" \
    "i)" "Nelson" \
    "j)" "Nelson GUI" \
    "k)" "Field" \
    3>&1 1>&2 2>&3
}

function services() {
    local CHOICE
    CHOICE=$(services_menu)
    RC=$?
    if [[ $RC -eq 1 ]]; then
        return
    fi
    case "$CHOICE" in

        "a)")
            service iri
            services
            ;;

        "b)")
            service iota-pm
            services
            ;;

        "c)")
            service prometheus
            services
            ;;

        "d)")
            service alertmanager
            services
            ;;

        "e)")
            service grafana-server
            services
            ;;

        "f)")
            service iota-prom-exporter
            services
            ;;

        "g)")
            service nginx
            services
            ;;

        "h)")
            service haproxy
            services
            ;;

        "i)")
           service nelson
           services
           ;;

        "j)")
           service nelson-gui
           services
           ;;

        "k)")
           service field
           services
           ;;

        *)
            services
            ;;
    esac
}

### Configure files ###
function configure_files_menu() {
    whiptail --title "IRIC v${VERSION} - Configure Files" \
             --menu "Choose an option" \
             --cancel-button "Back" \
              22 48 12 \
    "a)" "IRI System Config" \
    "b)" "IRI INI Config" \
    "c)" "IOTA Prom Expoter Config" \
    "d)" "AlertManager Config" \
    "e)" "Prometheus Config" \
    "f)" "Prometheus Alerts" \
    "g)" "Nelson Config" \
    "h)" "Field Config" \
    "Z)" "Choose Editor" \
    3>&1 1>&2 2>&3
}

function configure_files() {
    local CHOICE
    CHOICE=$(configure_files_menu)
    RC=$?
    if [[ $RC -eq 1 ]]; then
        return
    fi

    case "$CHOICE" in
        "a)")
            local IRI_CONFIG=$(grep ^file /root/.nbctl | cut -d: -f2 | sed 's/ //g')
            if [[ $? -ne 0 ]] || [ -z "$IRI_CONFIG" ]; then
                whiptail --title "Missing .nbctl data" \
                         --msgbox "Error: cannot find file value in $HOME/.nbctl" \
                         8 $WIDTH
                return 1
            fi
            edit_config "$IRI_CONFIG" "iri"
            configure_files
            ;;

        "b)")
            edit_config "/var/lib/iri/iri.ini" "iri"
            configure_files
            ;;

        "c)")
            edit_config "/opt/prometheus/iota-prom-exporter/config.js" "iota-prom-exporter"
            configure_files
            ;;

        "d)")
            edit_config "/opt/prometheus/alertmanager/config.yml" "alertmanager"
            configure_files
            ;;

        "e)")
            edit_config "/etc/prometheus/prometheus.yaml" "prometheus"
            configure_files
            ;;

        "f)")
            edit_config "/etc/prometheus/alert.rules.yml" "prometheus"
            configure_files
            ;;

        "g)")
            edit_config "/etc/nelson/nelson.ini" "nelson"
            configure_files
            ;;

        "h)")
            edit_config "/etc/field/field.ini" "field"
            configure_files
            ;;

        "Z)")
            choose_editor
            configure_files
            ;;

        *)
            configure_files
            ;;
    esac

}

### Neighbors ###
function neighbors_menu(){
    whiptail --title "IRIC v${VERSION} - Neighbors" \
             --menu "Choose an option" \
             --cancel-button "Back" \
              12 48 4 \
    "a)" "Add Neighbors" \
    "b)" "Remove neighbors" \
    "c)" "List neighbors" \
    3>&1 1>&2 2>&3
}

function neighbors(){
    local CHOICE
    CHOICE=$(neighbors_menu)
    RC=$?
    if [[ $RC -eq 1 ]]; then
        return
    fi

    case "$CHOICE" in
        "a)")
            add_neighbors
            neighbors
            ;;

        "b)")
            remove_neighbors
            neighbors
            ;;

        "c)")
            list_neighbors
            neighbors
            ;;

        *)
            neighbors
            ;;
    esac
}


function main_menu() {
    local MENU="Choose an option"
    if check_new_iric; then
        MENU="${MENU}\n(*IRIC update available)"
    fi

    whiptail --title "IRIC v${VERSION} - IRI Configuration Menu" \
             --menu "$MENU" \
             --cancel-button "Exit" \
              32 $WIDTH 22 \
    "a)" "Enable Nelson" \
    "b)" "Update Nelson" \
    "c)" "Enable Field" \
    "d)" "Update Field" \
    "e)" "Update IRI software" \
    "f)" "Update Monitoring" \
    "g)" "Enable HAProxy" \
    "h)" "Update HAProxy" \
    "i)" "Neighbors" \
    "j)" "Show LatestMilestoneIndex" \
    "k)" "Get Node Info" \
    "l)" "Manage Services" \
    "m)" "Get Fully Synced DB" \
    "n)" "Configure Files" \
    "o)" "View Per Processes Memory Usage" \
    "p)" "Update IRIC" \
    "Z)" "Configure this Script" \
    3>&1 1>&2 2>&3
}

function run_main_menu() {
    local CHOICE
    CHOICE=$(main_menu)
    RC=$?
    if [[ $RC -eq 1 ]]; then
        exit
    fi

    case "$CHOICE" in

        "Z)")
            how_to_setup
            run_main_menu
            ;;

        "a)")
            enable_nelson
            run_main_menu
            ;;

        "b)")
            upgrade_nelson
            run_main_menu
            ;;

        "c)")
            enable_field
            run_main_menu
            ;;

        "d)")
            upgrade_field
            run_main_menu
            ;;

        "e)")
            upgrade_iri
            run_main_menu
            ;;

        "f)")
            upgrade_monitoring
            run_main_menu
            ;;

        "g)")
            enable_haproxy
            run_main_menu
            ;;

        "h)")
            enable_haproxy "This will update the haproxy.cfg file to the latest version. Continue?"
            run_main_menu
            ;;

        "i)")
            neighbors
            run_main_menu
            ;;

        "j)")
            show_lmsi
            run_main_menu
            ;;

        "k)")
            get_node_info
            run_main_menu
            ;;

        "l)")
            services
            run_main_menu
            ;;

        "m)")
            get_db
            run_main_menu
            ;;

        "n)")
            configure_files
            run_main_menu
            ;;

        "o)")
            view_ps_mem
            run_main_menu
            ;;

        "p)")
            update_iric
            run_main_menu
            ;;

        *)
            run_main_menu
            ;;
    esac
}

run_main_menu
