- name: set variables centos
  set_fact:
    config_dir: /etc/sysconfig
  when: ansible_distribution == 'CentOS'

- name: set variables ubuntu/debian
  set_fact:
    config_dir: /etc/default
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- import_tasks: config.yml
  tags:
    - iotacaddy_config
