- name: ensure template directory exists for alertmanager
  file:
    path: "{{ alertmanager_basedir }}/template"
    state: directory

- name: 'download alertmanager docker image, this can take a moment...'
  docker_image:
    name: "{{ alertmanager_image }}"
    tag: "{{ alertmanager_tag }}"
  tags:
    - alertmanager_docker_image
  notify:
    - restart alertmanager

- name: copy email template for alertmanager
  template:
    src: templates/email.tmpl.j2
    dest: "{{ alertmanager_basedir }}/template/email.tmpl"
    force: "{{ overwrite | default('no') }}"
    backup: yes

- name: copy alertmanager sysconfig file
  template:
    src: templates/alertmanager.sysconfig.j2
    dest: "{{ config_dir }}/alertmanager"
    force: "{{ overwrite | default('no') }}"
  notify:
    - restart alertmanager

- name: copy alertmanager systemd service file
  template:
    src: templates/alertmanager.service.j2
    dest: "{{ systemd_dir }}/alertmanager.service"
  notify:
    - restart alertmanager

- name: copy alertmanager config
  template:
    force: "{{ overwrite | default('no') }}"
    backup: yes
    src: templates/alertmanager.cfg.yml.j2
    dest: "{{ alertmanager_basedir }}/config.yml"
    mode: 0600
    owner: "{{ prom_username }}"
    group: "{{ prom_username }}"
  notify:
    - restart alertmanager

- name: flush handlers
  meta: flush_handlers

- name: ensure alertmanager enabled and started
  systemd:
    name: alertmanager.service
    state: started
    enabled: yes
