- name: set empty fact
  set_fact:
    field_public_id: ''

- name: ensure config directory exists for field-exporter
  file:
    path: "{{ field_exporter_configdir }}"
    state: directory
    mode: 0700
    owner: "{{ prom_username }}"
    group: "{{ prom_username }}"

- name: 'download field_exporter docker image, this can take a moment...'
  docker_image:
    name: "{{ field_exporter_image }}"
    tag: "{{ field_exporter_tag }}"
  tags:
    - field_exporter_docker_image
  notify:
    - restart field-exporter

- name: install field-exporter config
  template:
    src: ../shared-files/field-exporter.config.js.j2
    dest: "{{ field_exporter_configdir }}/config.js"
    owner: "{{ prom_username }}"
    group: "{{ prom_username }}"
    force: "{{ overwrite | default('no') }}"
  notify:
    - restart field-exporter

- name: copy field-exporter sysconfig file
  template:
    src: field-exporter.sysconfig.j2
    dest: "{{ config_dir }}/field-exporter"
  notify:
    - restart field-exporter

- name: copy field-exporter systemd service file
  template:
    src: field-exporter.service.j2
    dest: "{{ systemd_dir }}/field-exporter.service"
  notify:
    - restart field-exporter

- name: flush handlers
  meta: flush_handlers

- name: start and enable field-exporter
  systemd:
    name: field-exporter.service
    state: started
    enabled: yes
