- name: set variables centos/redhat
  set_fact:
    systemd_dir: /usr/lib/systemd/system
    config_dir: /etc/sysconfig
  tags: always
  when: ansible_distribution == 'CentOS'

- name: set variables debian/ubuntu
  set_fact:
    systemd_dir: /lib/systemd/system
    config_dir: /etc/default
  tags: always
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: stat iota-prom-exporter basedir for git updates
  stat:
    path: "{{ iota_prom_exporter_basedir }}"
  register: iota_prom_exporter_basedir_git

- name: remove existing iota-prom-exporter dir
  file:
    path: "{{ iota_prom_exporter_basedir }}"
    state: absent
  when:
    - remove_iota_prom_exporter_basedir is defined
    - remove_iota_prom_exporter_basedir|bool == True

- name: create iota-prom-exporter dir
  file:
    path: "{{ iota_prom_exporter_basedir }}"
    state: directory
    owner: "{{ prom_username }}"
    group: "{{ prom_username }}"
    mode: 0700

- name: create iota-prom-exporter db dir
  file:
    path: "{{ iota_prom_exporter_basedir }}/db"
    state: directory
    owner: "{{ prom_username }}"
    group: "{{ prom_username }}"
    mode: 0700

- name: install iota-prom-exporter config
  template:
    src: templates/iota-prom-exporter.config.js.j2
    dest: "{{ iota_prom_exporter_basedir }}/config.js"
    owner: "{{ prom_username }}"
    group: "{{ prom_username }}"
    force: "{{ overwrite | default('no') }}"
  notify:
    - restart iota-prom-exporter

- name: copy iota-prom-exporter sysconfig file
  template:
    src: templates/iota-prom-exporter.sysconfig.j2
    dest: "{{ config_dir }}/iota-prom-exporter"
  notify:
    - restart iota-prom-exporter

- name: copy iota-prom-exporter systemd service file
  template:
    src: iota-prom-exporter.service.j2
    dest: "{{ systemd_dir }}/iota-prom-exporter.service"
    force: "{{ overwrite | default('no') }}"
  notify:
    - restart iota-prom-exporter

- import_tasks: image-iota-prom-exporter.yml
  tags:
    - iota_prom_exporter_docker_image

- name: flush handlers
  meta: flush_handlers

- name: start and enable iota-prom-exporter
  systemd:
    name: iota-prom-exporter.service
    state: started
    enabled: yes
