- name: restart nginx
  systemd:
    name: nginx.service
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: reload nginx
  systemd:
    name: nginx.service
    state: reloaded

- name: reload systemd
  command: systemctl daemon-reload
