- name: restart haproxy
  systemd:
    name: haproxy
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: reload haproxy
  systemd:
    name: haproxy
    state: reloaded
    enabled: yes

- name: restart rsyslog
  systemd:
    name: rsyslog
    state: restarted
    enabled: yes
