# Fix for recent addition of -RELEASE
# to file name on github :( 
# In the future the tag might move to the 
# tag portion of the URL ...
- name: set extra version tag for versions >= 1.5.6
  set_fact:
    iri_download_tag_version: "{{ iri_tag }}{{ '-RELEASE' if iri_version is version_compare('1.5.6', '>=') else '' }}"

- name: 'download iri docker image (on master), this can take a moment...'
  docker_image:
    name: "{{ iri_image }}"
    tag: "{{ iri_download_tag_version }}"
    force_source: "{{ force_pull_image | default('no') }}"
    source: pull
  notify:
    - restart iri
  register: download_image_status
  until: download_image_status is succeeded
  retries: 2
  delay: 5
  run_once: yes
  delegate_to: "{{ groups['fullnode']|first }}"
  when:
    - images_from_master is defined
    - images_from_master|bool == True

- name: 'download iri docker image, this can take a moment...'
  docker_image:
    name: "{{ iri_image }}"
    tag: "{{ iri_download_tag_version }}"
    force_source: "{{ force_pull_image | default('no') }}"
    source: pull
  notify:
    - restart iri
  register: download_image_status
  until: download_image_status is succeeded
  retries: 2
  delay: 5
  when: >
        images_from_master is not defined or
        images_from_master|bool == False

- name: remove -RELEASE from tag
  shell: "/usr/bin/docker tag {{ iri_image }}:{{ iri_download_tag_version }} {{ iri_image }}:{{ iri_tag }}"
  when: iri_version is version_compare('1.5.6', '>=')
  changed_when: False

- name: set image name and tag
  set_fact:
    this_tag: "{{ iri_tag }}"
    this_image: "{{ iri_image }}"

- name: set temporary image file name
  set_fact:
    this_file: "/tmp/image-iri-{{ this_tag }}.tar"

- name: image export and load block
  block:

    - name: check image exists
      shell: "/usr/bin/docker images {{ this_image }}:{{ this_tag }} | grep -q '^{{ this_image }}'"
      changed_when: False
      register: image_stat
      failed_when: "image_stat.rc > 1"

    - name: export the image to a file
      delegate_to: "{{ groups['fullnode']|first }}"
      docker_image:
        name: "{{ this_image }}"
        tag: "{{ this_tag }}"
        archive_path: "{{ this_file }}"
      when: "image_stat.rc == 1"

    - name: copy the docker image from the first node
      synchronize:
        src: "{{ this_file }}"
        dest: "{{ this_file }}"
      when: image_stat.rc == 1
      register: image_copied

    - name: load the image into docker
      docker_image:
        name: "{{ this_image }}"
        tag: "{{ this_tag }}"
        load_path: "{{ this_file }}"
        source: load
      when:
        - image_copied.changed
      notify:
        - restart iri

  when:
    - groups['fullnode'] | length > 1
    - inventory_hostname != groups['fullnode']|first

- name: remove image from temporary location
  file:
    path: "{{ this_file }}"
    state: absent
