- import_tasks: multi_nodes.yml
  tags:
    - multi_node_setup
  when: groups['fullnode'] | length > 1

- import_tasks: deps_apt.yml
  tags:
    - iri_deps_apt
  when:
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - install_system_deps | default(True) | bool

- import_tasks: deps_yum.yml
  tags:
    - iri_deps_yum
  when:
    - ansible_distribution == 'CentOS'
    - install_system_deps | default(True) | bool

- import_tasks: pip.yml
  tags:
    - py_docker

- import_tasks: logging.yml
  tags:
    - logging_config

- name: set ip variable if not set
  set_fact:
    ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
  when: ip is not defined
  tags:
    - expose_api_for_lb
    - consul_role
    - haproxy_ufw
    - haproxy_firewalld
    - loadbalancer_role

### Security ###
- name: proc hidepid option block
  block:

    - name: check /proc mount options
      shell: "/bin/mount | grep ^proc"
      args:
        warn: false
      register: mounted_hidepid
      failed_when: false
      changed_when: false

    # Note that ansible's mount module is unable to remount /proc.
    - name: remount /proc with hidepid=2
      shell: "/bin/mount -o remount,rw,hidepid=2 /proc"
      when: "'hidepid=2' not in mounted_hidepid.stdout"
      args:
        warn: false

    - name: remount /proc with hidepid=2 and configure fstab
      lineinfile:
        path: /etc/fstab
        regexp: "^proc "
        line: "proc           /proc            proc    rw,nosuid,nodev,noexec,relatime,hidepid=2     0     0"

  tags: proc_mount

- import_tasks: firewalld.yml
  tags:
    - iri_firewalld
  when:
    - ansible_distribution == 'CentOS'
    - configure_firewall | default(True) | bool

- import_tasks: ufw.yml
  tags:
    - iri_ufw
  when:
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - configure_firewall | default(True) | bool

- import_tasks: iri.yml
  tags:
    - iri_config

- import_tasks: ssl.yml
  tags:
    - iri_ssl

- import_tasks: uninstall.yml
  tags:
    - uninstall
    - uninstall_iri
  when: uninstall_playbook | default(False) | bool
