- import_tasks: deps_apt.yml
  tags:
    - iri_deps_apt
  when:
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - install_system_deps is defined and install_system_deps|bool == True

- import_tasks: deps_yum.yml
  tags:
    - iri_deps_yum
  when:
    - ansible_distribution == 'CentOS'
    - install_system_deps is defined and install_system_deps|bool == True

- import_tasks: pip.yml
  tags:
    - py_docker

- import_tasks: logging.yml
  tags:
    - logging_config

- import_tasks: firewalld.yml
  tags:
    - iri_firewalld
  when:
    - ansible_distribution == 'CentOS'
    - configure_firewall is defined and configure_firewall|bool == True

- import_tasks: ufw.yml
  tags:
    - iri_ufw
  when:
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - configure_firewall is defined and configure_firewall|bool == True

- import_tasks: iri.yml
  tags:
    - iri_config

- import_tasks: ssl.yml
  tags:
    - iri_ssl

- import_tasks: uninstall.yml
  tags:
    - uninstall
    - uninstall_iri
  when: uninstall_playbook is defined and uninstall_playbook|bool == True
