{
 "title": "IOTA",
 "tags": [
  "Home",
  "IOTA"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "neighbor",
    "label": "Neighbor IP",
    "query": "label_values(iota_neighbors_all_transactions, id)"
   },
   {
    "name": "server",
    "label": "Node",
    "query": "label_values(node_boot_time, instance)"
   },
   { "name": "pair", "label": "Trading Pair", "query": "label_values(pair)" }
  ]
 },
 "panels": [
  { "title": "IRI Node Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "LMI",
   "type": "singlestat",
   "description": "Latest Milestone Index",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "iota_node_info_latest_milestone"
    }
   ]
  },
  {
   "title": "Open Txs (Tips)",
   "type": "singlestat",
   "description": "There is no logical basis for the threshold definitions (7000 & 9500) other than anecdotal observations.",
   "gridPos": { "h": 6, "w": 5, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "iota_node_info_total_tips" }
   ]
  },
  {
   "title": "Total Txs",
   "type": "singlestat",
   "description": "This comes from the totalTransactions found in both rstats and getNodeInfo()",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "iota_zmq_total_transactions" }
   ]
  },
  {
   "title": "Txs to Request",
   "type": "singlestat",
   "description": "this is the toRequest line from rstats",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "iota_node_info_total_transactions_queued"
    }
   ]
  },
  {
   "title": "Avg Confirm Time",
   "type": "singlestat",
   "description": "10 minute rate for confirmation times (sum of confirmation times / count of confirmations)",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(iota_zmq_tx_confirm_time_sum[10m])/rate(iota_zmq_tx_confirm_time_count[10m]))"
    }
   ]
  },
  {
   "title": "Avg Confirm Rate",
   "type": "singlestat",
   "description": "10 minute avg of confirmations to seen transactions.",
   "gridPos": { "h": 6, "w": 3, "x": 16, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(rate(iota_zmq_confirmed_tx_count[10m])/rate(iota_zmq_seen_tx_count[10m]))"
    }
   ]
  },
  {
   "title": "Value to 0-value Txs",
   "type": "singlestat",
   "description": "Number of transactions with value divided by the number of 0-value transactions",
   "gridPos": { "h": 6, "w": 3, "x": 19, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(iota_zmq_seen_tx_count{hasValue=\"<> 0\"})/sum(iota_zmq_seen_tx_count{hasValue=\"0\"})"
    },
    {}
   ]
  },
  {
   "title": "Total Neighbors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "iota_node_info_total_neighbors", "legendFormat": "Neighbors" }
   ]
  },
  {
   "title": "LSMI",
   "type": "singlestat",
   "description": "Latest Subtangle Milestone Index",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "iota_node_info_latest_subtangle_milestone"
    }
   ]
  },
  {
   "title": "Active Neighbors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "iota_neighbors_active_neighbors"
    }
   ]
  },
  { "title": "Server Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent", "label": "cpu usage" }
   ],
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "AVG"
    },
    {
     "expr": "100 - (avg by (cpu) (irate(node_cpu_seconds_total{mode=\"idle\", instance=~\"$server\"}[5m])) * 100)",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Cached_bytes - node_memory_Buffers_bytes - node_memory_Slab_bytes",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~\"$server\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$server\"} + node_memory_Slab_bytes{instance=~\"$server\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$server\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "graph",
   "description": "IOTA mainnet database directory size",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "mainnetdb_dir_size_bytes", "legendFormat": "{{db_size}}" }
   ]
  },
  {
   "title": "Available Memory",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 8 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "( (node_memory_MemFree_bytes{instance=~\"$server\"} + node_memory_Cached_bytes{instance=~\"$server\"} + node_memory_Slab_bytes{instance=~\"$server\"} + node_memory_Buffers_bytes{instance=~\"$server\"} ) / node_memory_MemTotal_bytes{instance=~\"$server\"}) * 100 "
    }
   ]
  },
  {
   "title": "Free Filesystem",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 8 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(node_filesystem_free_bytes{fstype=~\"xfs|ext4\",instance=~\"$server\"} / node_filesystem_size_bytes{fstype=~\"xfs|ext4\",instance=~\"$server\"})"
    }
   ]
  },
  { "title": "ZMQ Metrics (local server)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "TPS vs CTPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(iota_zmq_seen_tx_count[3m])",
     "legendFormat": "TPS - val: {{hasValue}}"
    },
    {
     "expr": "rate(iota_zmq_confirmed_tx_count[3m])",
     "legendFormat": "CTPS - val: {{hasValue}}"
    },
    {
     "expr": "sum(rate(iota_zmq_seen_tx_count[10m]))",
     "legendFormat": "TPS Avg"
    },
    {
     "expr": "sum(rate(iota_zmq_confirmed_tx_count[10m]))",
     "legendFormat": "CTPS Avg"
    }
   ]
  },
  {
   "title": "Zero Value Txs vs Txs with Value",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(iota_zmq_seen_tx_count{hasValue=\"<> 0\"}[1m])",
     "legendFormat": "Value Txs"
    },
    {
     "expr": "delta(iota_zmq_seen_tx_count{hasValue=\"0\"}[1m])",
     "legendFormat": "Zero Value Txs"
    }
   ]
  },
  {
   "title": "Milestone Confirms vs Tips",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(iota_zmq_confirmed_tx_count[20s])",
     "legendFormat": "Value: {{hasValue}}"
    },
    { "expr": "iota_node_info_total_tips", "legendFormat": "Tips" }
   ]
  },
  { "title": "Confirmations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Avg Confirmation Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(iota_zmq_tx_confirm_time_sum[30m])/rate(iota_zmq_tx_confirm_time_count[30m])",
     "legendFormat": "30M Avg Time - val: {{hasValue}}"
    },
    {
     "expr": "rate(iota_zmq_tx_confirm_time_sum[10m])/rate(iota_zmq_tx_confirm_time_count[10m])",
     "legendFormat": "10M Avg Time - val: {{hasValue}}"
    }
   ]
  },
  {
   "title": "Confirmation Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(iota_zmq_confirmed_tx_count[30m])/rate(iota_zmq_seen_tx_count[30m])",
     "legendFormat": "30M Confirm rate - val: {{hasValue}}"
    },
    {
     "expr": "rate(iota_zmq_confirmed_tx_count[10m])/rate(iota_zmq_seen_tx_count[10m])",
     "legendFormat": "10M Confirm rate - val: {{hasValue}}"
    }
   ]
  },
  {
   "title": "Confirmations by Minute Buckets",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(rate(iota_zmq_tx_confirm_time_sum[5m])/rate(iota_zmq_tx_confirm_time_count[5m]))/60"
    }
   ]
  },
  { "title": "Market Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "IOTUSD Price",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "none", "label": "USD per MIOTA" }
   ],
   "targets": [
    {
     "expr": "iota_market_trade_price{pair=\"IOTUSD\"}",
     "legendFormat": "Price"
    },
    {
     "expr": "iota_market_trade_volume{pair=\"IOTUSD\"}",
     "legendFormat": "Volume"
    }
   ]
  },
  {
   "title": "BTCUSD",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "none", "label": "$USD to BTC" }
   ],
   "targets": [
    {
     "expr": "iota_market_trade_price{pair=\"BTCUSD\"}",
     "legendFormat": "Price"
    },
    {
     "expr": "iota_market_trade_volume{pair=\"BTCUSD\"}",
     "legendFormat": "Volume"
    }
   ]
  },
  {
   "title": "ETHUSD Price",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "Price" }
   ],
   "targets": [
    {
     "expr": "iota_market_trade_price{pair=\"ETHUSD\"}",
     "legendFormat": "price"
    },
    {
     "expr": "iota_market_trade_volume{pair=\"ETHUSD\"}",
     "legendFormat": "volume"
    }
   ]
  },
  {
   "title": "IOTETH Price",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "none", "label": "Price" }
   ],
   "targets": [
    {
     "expr": "iota_market_trade_price{pair=\"IOTETH\"}",
     "legendFormat": "Price"
    },
    {
     "expr": "iota_market_trade_volume{pair=\"IOTETH\"}",
     "legendFormat": "Volume"
    }
   ]
  },
  {
   "title": "IOTBTC Price",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "none", "label": "Price" }
   ],
   "targets": [
    {
     "expr": "iota_market_trade_price{pair=\"IOTBTC\"}",
     "legendFormat": "Price"
    },
    {
     "expr": "iota_market_trade_volume{pair=\"IOTBTC\"}",
     "legendFormat": "Volume"
    }
   ]
  },
  { "title": "All Neighbor Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "New Txs All Neighbors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short", "label": "Txs" }
   ],
   "targets": [
    {
     "expr": "delta(iota_neighbors_new_transactions[1m])"
    }
   ]
  },
  {
   "title": "Random Txs All Neighbors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 51 },
   "yaxes": [
    { "format": "short", "label": "Txs" }
   ],
   "targets": [
    {
     "expr": "delta(iota_neighbors_random_transactions[1m])"
    }
   ]
  },
  {
   "title": "All Txs All Neighbors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short", "label": "Txs" }
   ],
   "targets": [
    {
     "expr": "delta(iota_neighbors_all_transactions[1m])"
    }
   ]
  },
  {
   "title": "Invalid Txs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 51 },
   "yaxes": [
    { "format": "short", "label": "Txs" }
   ],
   "targets": [
    {
     "expr": "delta(iota_neighbors_invalid_transactions[1m])"
    }
   ]
  },
  {
   "title": "Stats By Neighbors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "$neighbor",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 59 },
     "repeat": "neighbor",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(iota_neighbors_new_transactions{id=~\"$neighbor\"}[1m])",
       "legendFormat": "New"
      },
      {
       "expr": "delta(iota_neighbors_random_transactions{id=~\"$neighbor\"}[1m])",
       "legendFormat": "Random"
      },
      {
       "expr": "delta(iota_neighbors_all_transactions{id=~\"$neighbor\"}[1m])",
       "legendFormat": "All"
      },
      {
       "expr": "delta(iota_neighbors_invalid_transactions{id=~\"$neighbor\"}[1m])",
       "legendFormat": "Invalid"
      },
      {
       "expr": "delta(iota_neighbors_sent_transactions{id=~\"$neighbor\"}[1m])",
       "legendFormat": "Sent"
      }
     ]
    },
    {
     "title": "$neighbor",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(iota_neighbors_new_transactions{id=~\"$neighbor\"}[1m])",
       "legendFormat": "New"
      },
      {
       "expr": "delta(iota_neighbors_random_transactions{id=~\"$neighbor\"}[1m])",
       "legendFormat": "Random"
      },
      {
       "expr": "delta(iota_neighbors_all_transactions{id=~\"$neighbor\"}[1m])",
       "legendFormat": "All"
      },
      {
       "expr": "delta(iota_neighbors_invalid_transactions{id=~\"$neighbor\"}[1m])",
       "legendFormat": "Invalid"
      },
      {
       "expr": "delta(iota_neighbors_sent_transactions{id=~\"$neighbor\"}[1m])",
       "legendFormat": "Sent"
      }
     ]
    },
    {
     "title": "$neighbor",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(iota_neighbors_new_transactions{id=~\"$neighbor\"}[1m])",
       "legendFormat": "New"
      },
      {
       "expr": "delta(iota_neighbors_random_transactions{id=~\"$neighbor\"}[1m])",
       "legendFormat": "Random"
      },
      {
       "expr": "delta(iota_neighbors_all_transactions{id=~\"$neighbor\"}[1m])",
       "legendFormat": "All"
      },
      {
       "expr": "delta(iota_neighbors_invalid_transactions{id=~\"$neighbor\"}[1m])",
       "legendFormat": "Invalid"
      },
      {
       "expr": "delta(iota_neighbors_sent_transactions{id=~\"$neighbor\"}[1m])",
       "legendFormat": "Sent"
      }
     ]
    },
    {
     "title": "$neighbor",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(iota_neighbors_new_transactions{id=~\"$neighbor\"}[1m])",
       "legendFormat": "New"
      },
      {
       "expr": "delta(iota_neighbors_random_transactions{id=~\"$neighbor\"}[1m])",
       "legendFormat": "Random"
      },
      {
       "expr": "delta(iota_neighbors_all_transactions{id=~\"$neighbor\"}[1m])",
       "legendFormat": "All"
      },
      {
       "expr": "delta(iota_neighbors_invalid_transactions{id=~\"$neighbor\"}[1m])",
       "legendFormat": "Invalid"
      },
      {
       "expr": "delta(iota_neighbors_sent_transactions{id=~\"$neighbor\"}[1m])",
       "legendFormat": "Sent"
      }
     ]
    }
   ]
  },
  {
   "title": "alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "collapsed": true,
   "panels": [
    {
     "title": "Neighbor Count",
     "type": "graph",
     "description": "Used for alerting only",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "iota_node_info_total_neighbors", "legendFormat": "Neighbors" }
     ]
    },
    {
     "title": "Dead Neighbor Count",
     "type": "graph",
     "description": "For alerting purposes",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(iota_node_info_total_neighbors - iota_neighbors_active_neighbors)  ",
       "legendFormat": "Dead neighbors"
      }
     ]
    },
    {
     "title": "Milestone",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "iota_node_info_latest_milestone - iota_node_info_latest_subtangle_milestone",
       "legendFormat": "Milestone Delta"
      }
     ]
    },
    {
     "title": "Free Filesystem Space",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 59 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(node_filesystem_free_bytes{fstype=~\"xfs|ext4\"} / node_filesystem_size_bytes{fstype=~\"xfs|ext4\"})",
       "legendFormat": "Free Filesystem"
      }
     ]
    }
   ]
  }
 ]
}