{
 "title": "Node Exporter",
 "description": "Node Exporter production dashboard by fangdd.com",
 "tags": [ "ops" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(node_boot_time, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Basic CPU / Mem / Net Gauge", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Busy Now",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(((count(count(node_cpu{instance=~\"$node:.*\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu{mode='idle',instance=~\"$node:.*\"}[5m])))) * 100) / count(count(node_cpu{instance=~\"$node:.*\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Used RAM Memory",
   "type": "singlestat",
   "description": "Used RAM Memory without swap and cache",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((node_memory_MemTotal{instance=~\"$node:.*\"} - node_memory_MemFree{instance=~\"$node:.*\"} - node_memory_Cached{instance=~\"$node:.*\"}) / (node_memory_MemTotal{instance=~\"$node:.*\"} )) * 100"
    }
   ]
  },
  {
   "title": "Used SWAP",
   "type": "singlestat",
   "description": "Used Swap",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((node_memory_SwapTotal{instance=~\"$node:.*\"} - node_memory_SwapFree{instance=~\"$node:.*\"}) / (node_memory_SwapTotal{instance=~\"$node:.*\"} )) * 100"
    }
   ]
  },
  {
   "title": "CPU System Load (1m avg)",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together (1 min average)",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_load1{instance=~\"$node:.*\"}) /  count(count(node_cpu{instance=~\"$node:.*\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "description": "Basic network info per interface.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes{instance=~\"$node:.*\"}[5m])",
     "legendFormat": "recv bytes {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes{instance=~\"$node:.*\"}[5m])",
     "legendFormat": "trans bytes {{device}} "
    }
   ]
  },
  { "title": "Basic CPU / Mem / Net Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu{instance=~\"$node:.*\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "singlestat",
   "description": "Total RAM",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal{instance=~\"$node:.*\"}"
    }
   ]
  },
  {
   "title": "Total SWAP",
   "type": "singlestat",
   "description": "Total SWAP",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 7 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_SwapTotal{instance=~\"$node:.*\"}"
    }
   ]
  },
  {
   "title": "System Load (1m avg)",
   "type": "singlestat",
   "description": "System Load (1m avg)",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node:.*\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "System uptime",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 7 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_time{instance=~\"$node:.*\"} - node_boot_time{instance=~\"$node:.*\"}"
    }
   ]
  },
  {
   "title": "Used RootFS",
   "type": "singlestat",
   "description": "Used RootFS",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((node_filesystem_size{device=~\"rootfs\",instance=~\"$node:.*\"} - node_filesystem_free{device=~\"rootfs\",instance=~\"$node:.*\"}) * 100 ) / (node_filesystem_size{device=~\"rootfs\",instance=~\"$node:.*\"})"
    }
   ]
  },
  { "title": "Basic CPU / Mem Graph", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "CPU Basic",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum ( irate(node_cpu{mode!='idle',instance=~\"$node:.*\"}[5m]))",
     "legendFormat": "Busy"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='idle',instance=~\"$node:.*\"}[5m]))",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal{instance=~\"$node:.*\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal{instance=~\"$node:.*\"} - node_memory_MemFree{instance=~\"$node:.*\"} - node_memory_Cached{instance=~\"$node:.*\"} - node_memory_Buffers{instance=~\"$node:.*\"} - node_memory_Slab{instance=~\"$node:.*\"}",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "(node_memory_SwapTotal{instance=~\"$node:.*\"} - node_memory_SwapFree{instance=~\"$node:.*\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  { "title": "Basic Filesystem Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Filesystem Usage",
   "type": "table",
   "description": "Local filesystem usage",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "100 - (node_filesystem_free{instance=~\"$node:.*\",fstype=~\"xfs|ext4\"} / node_filesystem_size{instance=~\"$node:.*\",fstype=~\"xfs|ext4\"} * 100)",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  },
  {
   "title": "Filesystem Size",
   "type": "table",
   "description": "Local filesystem sIze info",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 20 },
   "targets": [
    {
     "expr": "node_filesystem_size{instance=~\"$node:.*\",fstype=~\"xfs|ext4\"}",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node:.*\"}",
     "legendFormat": "load 1"
    },
    {
     "expr": "node_load5{instance=~\"$node:.*\"}",
     "legendFormat": "load 5"
    },
    {
     "expr": "node_load15{instance=~\"$node:.*\"}",
     "legendFormat": "load 15"
    }
   ]
  },
  { "title": "CPU Memory Net Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "CPU",
   "type": "graph",
   "description": "CPU info",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (mode)(irate(node_cpu{mode=\"system\",instance=~\"$node:.*\"}[5m]))",
     "legendFormat": "System - Processes executing in kernel mode"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='user',instance=~\"$node:.*\"}[5m]))",
     "legendFormat": "User - Normal processes executing in user mode"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='nice',instance=~\"$node:.*\"}[5m]))",
     "legendFormat": "Nice - Niced processes executing in user mode"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='idle',instance=~\"$node:.*\"}[5m]))",
     "legendFormat": "Idle - Waiting for something to happen"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='iowait',instance=~\"$node:.*\"}[5m]))",
     "legendFormat": "Iowait - Waiting for I/O to complete"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='irq',instance=~\"$node:.*\"}[5m]))",
     "legendFormat": "Irq - Servicing interrupts"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='softirq',instance=~\"$node:.*\"}[5m]))",
     "legendFormat": "Softirq - Servicing softirqs"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='steal',instance=~\"$node:.*\"}[5m]))",
     "legendFormat": "Steal - Time spent in other operating systems when running in a virtualized environment"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='guest',instance=~\"$node:.*\"}[5m]))",
     "legendFormat": "Guest - Time spent running a virtual CPU for a guest operating system"
    }
   ]
  },
  {
   "title": "Memory Stack",
   "type": "graph",
   "description": "Memory Stack",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal{instance=~\"$node:.*\"} - node_memory_MemFree{instance=~\"$node:.*\"} - node_memory_Buffers{instance=~\"$node:.*\"} - node_memory_Cached{instance=~\"$node:.*\"} - node_memory_Slab{instance=~\"$node:.*\"} - node_memory_PageTables{instance=~\"$node:.*\"} - node_memory_SwapCached{instance=~\"$node:.*\"}",
     "legendFormat": "Apps - Memory used by processes"
    },
    {
     "expr": "node_memory_PageTables{instance=~\"$node:.*\"}",
     "legendFormat": "PageTables - Memory dedicated to the lowest page table level"
    },
    {
     "expr": "node_memory_SwapCached{instance=~\"$node:.*\"}",
     "legendFormat": "SwapCache - Swap used as cache memory"
    },
    {
     "expr": "node_memory_Slab{instance=~\"$node:.*\"}",
     "legendFormat": "Slab - Memory used by the kernel to cache data structures for its own use"
    },
    {
     "expr": "node_memory_Cached{instance=~\"$node:.*\"}",
     "legendFormat": "Cache - Physical RAM used as cache memory"
    },
    {
     "expr": "node_memory_Buffers{instance=~\"$node:.*\"}",
     "legendFormat": "Buffers - Physical RAM used for file buffers"
    },
    {
     "expr": "node_memory_MemFree{instance=~\"$node:.*\"}",
     "legendFormat": "Unused - Free memory unasigned"
    },
    {
     "expr": "(node_memory_SwapTotal{instance=~\"$node:.*\"} - node_memory_SwapFree{instance=~\"$node:.*\"})",
     "legendFormat": "Swap - Swap memory usage"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes{instance=~\"$node:.*\"}[5m])",
     "legendFormat": "{{device}} receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes{instance=~\"$node:.*\"}[5m])",
     "legendFormat": "{{device}} transmit"
    }
   ]
  },
  {
   "title": "I/O Usage Read / Write",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_bytes_read{instance=~\"$node:.*\",device=~\"[a-z]*[a-z]\"}[5m])",
     "legendFormat": "successfully read bytes {{device}}"
    },
    {
     "expr": "irate(node_disk_bytes_written{instance=~\"$node:.*\",device=~\"[a-z]*[a-z]\"}[5m])",
     "legendFormat": "successfully written bytes {{device}}"
    }
   ]
  },
  {
   "title": "I/O Usage Times",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_ms{instance=~\"$node:.*\",device=~\"[a-z]*[a-z]\"} [5m])",
     "legendFormat": "milliseconds spent doing I/Os {{device}}"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "graph",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100- ((node_filesystem_avail{instance=~\"$node:.*\",device!~'rootfs'} * 100) / node_filesystem_size{instance=~\"$node:.*\",device!~'rootfs'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "Memory Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Committed_AS{instance=~\"$node:.*\"}",
     "legendFormat": "Committed - The amount of memory presently allocated on the system"
    },
    {
     "expr": "node_memory_Mapped{instance=~\"$node:.*\"}",
     "legendFormat": "Mapped - Files which have been mmaped, such as libraries"
    },
    {
     "expr": "node_memory_Active{instance=~\"$node:.*\"}",
     "legendFormat": "Active - Memory that has been used more recently and usually not reclaimed unless absolutely necessary"
    },
    {
     "expr": "node_memory_Inactive{instance=~\"$node:.*\"}",
     "legendFormat": "Inactive - Memory which has been less recently used.  It is more eligible to be reclaimed for other purposes"
    },
    {
     "expr": "node_memory_VmallocUsed{instance=~\"$node:.*\"}",
     "legendFormat": "VmallocUsed - Memory of used virtual address space"
    },
    {
     "expr": "node_memory_CommitLimit{instance=~\"$node:.*\"}",
     "legendFormat": "Commit Limit - Total amount of  memory currently available to be allocated on the system"
    },
    {
     "expr": "node_memory_Dirty{instance=~\"$node:.*\"}",
     "legendFormat": "Dirty - Memory which is waiting to get written back to the disk"
    },
    {
     "expr": "node_memory_HardwareCorrupted{instance=~\"$node:.*\"}",
     "legendFormat": "Harware Corrupted - Amount of RAM that the kernel identified as corrupted / not working"
    },
    {
     "expr": "node_memory_Unevictable{instance=~\"$node:.*\"}",
     "legendFormat": "Unevictable - Unevictable pages can't be swapped out for a variety of reasons"
    },
    {
     "expr": "node_memory_Shmem{instance=~\"$node:.*\"}",
     "legendFormat": "Shared mem - Total memory used by shared memory (shmem) and tmpfs"
    },
    {
     "expr": "node_memory_Mlocked{instance=~\"$node:.*\"}",
     "legendFormat": "MLocked - Pages locked to memory using the mlock() system call"
    }
   ]
  },
  {
   "title": "Swap in/out",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_vmstat_pswpin {instance=~\"$node:.*\"}[5m])",
     "legendFormat": "swap_in - Pages per second int"
    },
    {
     "expr": "irate(node_vmstat_pswpout{instance=~\"$node:.*\"}[5m])",
     "legendFormat": "swap_out - Pages per second out"
    }
   ]
  },
  {
   "title": "Memory Writeback",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 97 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Writeback{instance=~\"$node:.*\"}",
     "legendFormat": "Writeback - Memory which is actively being written back to disk"
    },
    {
     "expr": "node_memory_WritebackTmp{instance=~\"$node:.*\"}",
     "legendFormat": "WritebackTmp - Memory used by FUSE for temporary writeback buffers"
    }
   ]
  },
  {
   "title": "Memory Active / Inactive File",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Active_file{instance=~\"$node:.*\"}",
     "legendFormat": "Active File - File-backed memory on active LRU list"
    },
    {
     "expr": "node_memory_Inactive_file{instance=~\"$node:.*\"}",
     "legendFormat": "Inactive File - File-backed memory on inactive LRU list"
    }
   ]
  },
  {
   "title": "Memory Usage Vmalloc",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 107 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_VmallocChunk{instance=~\"$node:.*\"}",
     "legendFormat": "VmallocChunk - Largest contiguous block of vmalloc area which is free"
    },
    {
     "expr": "node_memory_VmallocTotal{instance=~\"$node:.*\"}",
     "legendFormat": "VmallocTotal - Total size of vmalloc memory area"
    },
    {
     "expr": "node_memory_VmallocUsed{instance=~\"$node:.*\"}",
     "legendFormat": "VmallocUsed - Amount of vmalloc area which is used"
    }
   ]
  },
  {
   "title": "Memory Usage HugePages",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 117 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_HugePages_Free{instance=~\"$node:.*\"}",
     "legendFormat": "HugePages Free - Number of huge pages in the pool that are not yet allocated"
    },
    {
     "expr": "node_memory_HugePages_Rsvd{instance=~\"$node:.*\"}",
     "legendFormat": "HugePages Reserved - Number of huge pages for                 which a commitment to allocate from the pool has been made,                 but no allocation has yet been made"
    },
    {
     "expr": "node_memory_HugePages_Surp{instance=~\"$node:.*\"}",
     "legendFormat": "HugePages Surp - Number of huge pages in                 the pool above the value in /proc/sys/vm/nr_hugepages"
    },
    {
     "expr": "node_memory_HugePages_Total{instance=~\"$node:.*\"}",
     "legendFormat": "HugePages - Total size of the pool of huge pages"
    },
    {
     "expr": "node_memory_Hugepagesize{instance=~\"$node:.*\"}",
     "legendFormat": "Hugepagesize - Huge Page size"
    }
   ]
  },
  {
   "title": "Memory DirectMap",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 117 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_DirectMap1G{instance=~\"$node:.*\"}",
     "legendFormat": "DirectMap1G - Amount of pages mapped as this size"
    },
    {
     "expr": "node_memory_DirectMap2M{instance=~\"$node:.*\"}",
     "legendFormat": "DirectMap2M - Amount of pages mapped as this size"
    },
    {
     "expr": "node_memory_DirectMap4k{instance=~\"$node:.*\"}",
     "legendFormat": "DirectMap4K  - Amount of pages mapped as this size"
    }
   ]
  },
  {
   "title": "Memory Anon",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 127 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_AnonHugePages{instance=~\"$node:.*\"}",
     "legendFormat": "Anon Huge Pages - Non-file backed huge pages mapped into userspace page tables"
    },
    {
     "expr": "node_memory_AnonPages{instance=~\"$node:.*\"}",
     "legendFormat": "Anon Pages - Non-file backed pages mapped into userspace page tables"
    },
    {
     "expr": "node_memory_Active_anon{instance=~\"$node:.*\"}",
     "legendFormat": "Inactive Anon - Anonymous and swap cache on inactive LRU list, including tmpfs (shmem)"
    }
   ]
  },
  {
   "title": "Memory Reclaimed",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 127 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_SReclaimable{instance=~\"$node:.*\"}",
     "legendFormat": "SReclaimable - Part of Slab, that might be reclaimed, such as caches"
    },
    {
     "expr": "node_memory_SUnreclaim{instance=~\"$node:.*\"}",
     "legendFormat": "SUnreclaim - Part of Slab, that cannot be reclaimed on memory pressure"
    }
   ]
  },
  {
   "title": "Memory NFS",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 137 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_NFS_Unstable{instance=~\"$node:.*\"}",
     "legendFormat": "NFS Unstable - NFS pages sent to the server, but not yet commited to the storage"
    }
   ]
  },
  {
   "title": "System Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 147 },
   "collapsed": true,
   "panels": [
    {
     "title": "Context Switches / Interrupts / Entropy",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 148 },
     "repeat": "node",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(node_context_switches{instance=~\"$node:.*\"}[5m])",
       "legendFormat": "Context switches"
      },
      {
       "expr": "irate(node_intr{instance=~\"$node:.*\"}[5m])",
       "legendFormat": "Interrupts"
      },
      {
       "expr": "node_entropy_available_bits{instance=~\"$node:.*\"}",
       "legendFormat": "Entropy"
      }
     ]
    },
    {
     "title": "System Load",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 156 },
     "repeat": "node",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load1{instance=~\"$node:.*\"}",
       "legendFormat": "Load 1m"
      },
      {
       "expr": "node_load5{instance=~\"$node:.*\"}",
       "legendFormat": "Load 5m"
      },
      {
       "expr": "node_load15{instance=~\"$node:.*\"}",
       "legendFormat": "Load 15m"
      }
     ]
    },
    {
     "title": "Processes State / Forks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 164 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_procs_blocked{instance=~\"$node:.*\"}",
       "legendFormat": "Processes blocked waiting for I/O to complete"
      },
      {
       "expr": "node_procs_running{instance=~\"$node:.*\"}",
       "legendFormat": "Processes in runnable state"
      },
      {
       "expr": "increase(node_forks{instance=~\"$node:.*\"}[5m])",
       "legendFormat": "Processes forks"
      }
     ]
    },
    {
     "title": "File Descriptors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 172 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_max_fds{instance=~\"$node:.*\"}",
       "legendFormat": "Max file descriptors"
      },
      {
       "expr": "process_open_fds{instance=~\"$node:.*\"}",
       "legendFormat": "Open file descriptors"
      }
     ]
    },
    {
     "title": "Processes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 172 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{instance=~\"$node:.*\"}",
       "legendFormat": "Resident memory size in bytes"
      },
      {
       "expr": "process_start_time_seconds{instance=~\"$node:.*\"}",
       "legendFormat": "Start time of the process since unix epoch in seconds"
      },
      {
       "expr": "process_virtual_memory_bytes{instance=~\"$node:.*\"}",
       "legendFormat": "Virtual memory size in bytes"
      }
     ]
    }
   ]
  },
  { "title": "Disk Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 148 } },
  {
   "title": "Disk R/W",
   "type": "graph",
   "description": "The total number of bytes read / write successfully.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 149 },
   "yaxes": [
    { "format": "bytes", "label": "read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_bytes_read{instance=~\"$node:.*\"}[5m])",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_bytes_written{instance=~\"$node:.*\"}[5m])",
     "legendFormat": "{{device}}_written"
    }
   ]
  },
  {
   "title": "Disk IOs",
   "type": "graph",
   "description": "Total number of reads / writes completed successfully",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 158 },
   "yaxes": [
    { "format": "iops", "label": "IO/second read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed{instance=~\"$node:.*\"}[5m])",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_writes_completed{instance=~\"$node:.*\"}[5m])",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  {
   "title": "Disk R/W miliseconds",
   "type": "graph",
   "description": "The total number of milliseconds spent by all reads / writes.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 167 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_time_ms{instance=~\"$node:.*\"}[5m])",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_write_time_ms{instance=~\"$node:.*\"}[5m])",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  {
   "title": "Disk IOs weighted",
   "type": "graph",
   "description": "The weighted # of milliseconds spent doing I/Os. This field is incremented at each I/O start, I/O completion, I/O  merge, or read of these stats by the number of I/Os in progress times the number of milliseconds spent doing I/O since the last update of this field. This can provide an easy measure of both I/O completion time and the backlog that may be accumulating.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 167 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_weighted{instance=~\"$node:.*\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk R/W Merged",
   "type": "graph",
   "description": "The total number of  reads merged. See https://www.kernel.org/doc/Documentation/iostats.txt.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 176 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_merged{instance=~\"$node:.*\"}[5m])",
     "legendFormat": "{{device}}_merged_read"
    },
    {
     "expr": "irate(node_disk_writes_mergedd{instance=~\"$node:.*\"}[5m])",
     "legendFormat": "{{device}}_merged_write"
    }
   ]
  },
  {
   "title": "Disk IOs current in progress",
   "type": "graph",
   "description": "The number of I/Os currently in progress.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 176 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_now{instance=~\"$node:.*\"}[5m])",
     "legendFormat": "{{device}} "
    }
   ]
  },
  {
   "title": "Disk R/W completed",
   "type": "graph",
   "description": "The total number of reads / writes completed successfully. See https://www.kernel.org/doc/Documentation/iostats.txt.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 185 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed{instance=~\"$node:.*\"}[5m])",
     "legendFormat": "{{device}}_completed_read"
    },
    {
     "expr": "irate(node_disk_writes_completed{instance=~\"$node:.*\"}[5m])",
     "legendFormat": "{{device}}_completed_write"
    }
   ]
  },
  {
   "title": "Milliseconds spent doing I/Os",
   "type": "graph",
   "description": "Milliseconds spent doing I/Os.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 185 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_ms{instance=~\"$node:.*\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Sectors read / write succesfully",
   "type": "graph",
   "description": "The total number of sectors read successfully.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 194 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_sectors_read{instance=~\"$node.*\"}[5m])",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_sectors_written{instance=~\"$node.*\"}[5m])",
     "legendFormat": "{{device}}_written"
    }
   ]
  },
  {
   "title": "Open error file",
   "type": "graph",
   "description": "1 if there was an error opening or reading a file, 0 otherwise",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 194 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_textfile_scrape_error{instance=~\"$node:.*\"}",
     "legendFormat": "read error"
    }
   ]
  },
  { "title": "Filesystem Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 203 } },
  {
   "title": "Filesystem space available",
   "type": "graph",
   "description": "Filesystem space available to non-root users in bytes. Filesystem free space in bytes. Filesystem read-only status. Filesystem size in bytes.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 204 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail{instance=~\"$node:.*\",device!~'rootfs'}",
     "legendFormat": "{{mountpoint}} Available"
    }
   ]
  },
  {
   "title": "File nodes",
   "type": "graph",
   "description": "Filesystem total file nodes.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 214 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_files{instance=~\"$node:.*\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "File descriptor",
   "type": "graph",
   "description": "File descriptor statistics: allocated.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 224 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filefd_maximum{instance=~\"$node:.*\"}",
     "legendFormat": "max open files"
    },
    {
     "expr": "node_filefd_allocated{instance=~\"$node:.*\"}",
     "legendFormat": "open files"
    }
   ]
  },
  {
   "title": "Filesystem in ReadOnly",
   "type": "graph",
   "description": "Filesystem read-only status.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 224 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_readonly{instance=~\"$node:.*\",device!~'rootfs'}",
     "legendFormat": "{{mountpoint}} ReadOnly"
    }
   ]
  },
  { "title": "Network traffic Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 234 } },
  {
   "title": "Network Traffic by Packets",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 235 },
   "yaxes": [
    { "format": "pps", "label": "Packets per second" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_packets{instance=~\"$node.*\"}[5m])",
     "legendFormat": "{{device}} receive"
    },
    {
     "expr": "irate(node_network_transmit_packets{instance=~\"$node.*\"}[5m])",
     "legendFormat": "{{device}} transmit"
    }
   ]
  },
  {
   "title": "Network Traffic Detail",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 245 },
   "yaxes": [
    { "format": "pps", "label": "Packets per second" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_compressed{instance=~\"$node.*\"}[5m])",
     "legendFormat": "{{device}} receive compressed"
    },
    {
     "expr": "irate(node_network_transmit_compressed{instance=~\"$node.*\"}[5m])",
     "legendFormat": "{{device}} transmit compressed"
    },
    {
     "expr": "irate(node_network_receive_errs{instance=~\"$node.*\"}[5m])",
     "legendFormat": "{{device}} receive errors"
    },
    {
     "expr": "irate(node_network_transmit_errs{instance=~\"$node.*\"}[5m])",
     "legendFormat": "{{device}} transmit errors"
    },
    {
     "expr": "irate(node_network_receive_drop{instance=~\"$node.*\"}[5m])",
     "legendFormat": "{{device}} receive drop"
    },
    {
     "expr": "irate(node_network_transmit_drop{instance=~\"$node.*\"}[5m])",
     "legendFormat": "{{device}} transmit drop"
    },
    {
     "expr": "irate(node_network_receive_fifo{instance=~\"$node.*\"}[5m])",
     "legendFormat": "{{device}} receive fifo"
    },
    {
     "expr": "irate(node_network_transmit_fifo{instance=~\"$node.*\"}[5m])",
     "legendFormat": "{{device}} transmit fifo"
    },
    {
     "expr": "irate(node_network_receive_multicast{instance=~\"$node.*\"}[5m])",
     "legendFormat": "{{device}} receive multicast"
    },
    {
     "expr": "irate(node_network_transmit_multicast{instance=~\"$node.*\"}[5m])",
     "legendFormat": "{{device}} transmit multicast"
    }
   ]
  },
  {
   "title": "NF Contrack",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 255 },
   "yaxes": [
    { "format": "short", "label": "Entries" }
   ],
   "targets": [
    {
     "expr": "node_nf_conntrack_entries{instance=~\"$node.*\"}",
     "legendFormat": "nf conntrack entries"
    },
    {
     "expr": "node_nf_conntrack_entries_limit{instance=~\"$node.*\"}",
     "legendFormat": "nf conntrack limit"
    }
   ]
  },
  { "title": "Network Sockstat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 265 } },
  {
   "title": "Sockstat TCP",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 266 },
   "yaxes": [
    { "format": "short", "label": "sockets" }
   ],
   "targets": [
    {
     "expr": "node_sockstat_TCP_alloc{instance=~\"$node.*\"}",
     "legendFormat": "TCP_alloc"
    },
    {
     "expr": "node_sockstat_TCP_inuse{instance=~\"$node.*\"}",
     "legendFormat": "TCP_inuse"
    },
    {
     "expr": "node_sockstat_TCP_mem{instance=~\"$node.*\"}",
     "legendFormat": "TCP_mem"
    },
    {
     "expr": "node_sockstat_TCP_mem_bytes{instance=~\"$node.*\"}",
     "legendFormat": "TCP_mem_bytes"
    },
    {
     "expr": "node_sockstat_TCP_orphan{instance=~\"$node.*\"}",
     "legendFormat": "TCP_orphan"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=~\"$node.*\"}",
     "legendFormat": "TCP_tw"
    }
   ]
  },
  {
   "title": "Sockstat UDP",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 266 },
   "yaxes": [
    { "format": "short", "label": "sockets" }
   ],
   "targets": [
    {
     "expr": "node_sockstat_UDPLITE_inuse{instance=~\"$node.*\"}",
     "legendFormat": "UDPLITE_inuse"
    },
    {
     "expr": "node_sockstat_UDP_inuse{instance=~\"$node.*\"}",
     "legendFormat": "UDP_inuse"
    },
    {
     "expr": "node_sockstat_UDP_mem{instance=~\"$node.*\"}",
     "legendFormat": "UDP_mem"
    },
    {
     "expr": "node_sockstat_UDP_mem_bytes{instance=~\"$node.*\"}",
     "legendFormat": "UDP_mem_bytes"
    }
   ]
  },
  {
   "title": "Sockstat Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 275 },
   "yaxes": [
    { "format": "short", "label": "sockets" }
   ],
   "targets": [
    {
     "expr": "node_sockstat_sockets_used{instance=~\"$node.*\"}",
     "legendFormat": "Sockets_used"
    }
   ]
  },
  {
   "title": "Sockstat FRAG / RAW",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 275 },
   "yaxes": [
    { "format": "short", "label": "sockets" }
   ],
   "targets": [
    {
     "expr": "node_sockstat_FRAG_inuse{instance=~\"$node.*\"}",
     "legendFormat": "FRAG_inuse"
    },
    {
     "expr": "node_sockstat_FRAG_memory{instance=~\"$node.*\"}",
     "legendFormat": "FRAG_memory"
    },
    {
     "expr": "node_sockstat_RAW_inuse{instance=~\"$node.*\"}",
     "legendFormat": "RAW_inuse"
    }
   ]
  },
  { "title": "Network Netstat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 284 } },
  {
   "title": "Netstat IP Errors / Discards",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 285 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Ip_InDiscards{instance=~\"$node..*\"}[5m])",
     "legendFormat": "InDiscards"
    },
    {
     "expr": "irate(node_netstat_Ip_InHdrErrors{instance=~\"$node..*\"}[5m])",
     "legendFormat": "InHdrErrors"
    },
    {
     "expr": "irate(node_netstat_Ip_InUnknownProtos{instance=~\"$node..*\"}[5m])",
     "legendFormat": "InUnknownProtos"
    },
    {
     "expr": "irate(node_netstat_Ip_OutDiscards{instance=~\"$node..*\"}[5m])",
     "legendFormat": "OutDiscards"
    },
    {
     "expr": "irate(node_netstat_Ip_OutNoRoutes{instance=~\"$node..*\"}[5m])",
     "legendFormat": "OutNoRoutes"
    },
    {
     "expr": "irate(node_netstat_IpExt_InNoRoutes{instance=~\"$node..*\"}[5m])",
     "legendFormat": "InNoRoutes"
    },
    {
     "expr": "irate(node_netstat_IpExt_InCsumErrors{instance=~\"$node..*\"}[5m])",
     "legendFormat": "InCsumErrors"
    },
    {
     "expr": "irate(node_netstat_IpExt_InTruncatedPkts{instance=~\"$node..*\"}[5m])",
     "legendFormat": "InTruncatedPkts"
    }
   ]
  },
  {
   "title": "Netstat IP Receive / Deliver",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 285 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Ip_InReceives{instance=~\"$node..*\"}[5m])",
     "legendFormat": "InReceives"
    },
    {
     "expr": "irate(node_netstat_Ip_InDelivers{instance=~\"$node..*\"}[5m])",
     "legendFormat": "InDelivers"
    },
    {
     "expr": "irate(node_netstat_Ip_OutRequests{instance=~\"$node..*\"}[5m])",
     "legendFormat": "OutRequests"
    }
   ]
  },
  {
   "title": "Netstat IP Bcast",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 293 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_IpExt_InBcastOctets{instance=~\"$node..*\"}[5m])",
     "legendFormat": "InBcastOctets"
    },
    {
     "expr": "irate(node_netstat_IpExt_InBcastPkts{instance=~\"$node..*\"}[5m])",
     "legendFormat": "InBcastPkts"
    },
    {
     "expr": "irate(node_netstat_IpExt_OutBcastOctets{instance=~\"$node..*\"}[5m])",
     "legendFormat": "OutBcastOctets"
    },
    {
     "expr": "irate(node_netstat_IpExt_OutBcastPkts{instance=~\"$node..*\"}[5m])",
     "legendFormat": "OutBcastPkts"
    }
   ]
  },
  {
   "title": "Netstat IP Mcast",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 293 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_IpExt_InMcastOctets{instance=~\"$node..*\"}[5m])",
     "legendFormat": "InMcastOctets"
    },
    {
     "expr": "irate(node_netstat_IpExt_InMcastPkts{instance=~\"$node..*\"}[5m])",
     "legendFormat": "InMcastPkts"
    },
    {
     "expr": "irate(node_netstat_IpExt_OutMcastOctets{instance=~\"$node..*\"}[5m])",
     "legendFormat": "OutMcastOctets"
    },
    {
     "expr": "irate(node_netstat_IpExt_OutMcastPkts{instance=~\"$node..*\"}[5m])",
     "legendFormat": "OutMcastPkts"
    }
   ]
  },
  {
   "title": "Netstat IP Octets / ECT / CEP",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 301 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_IpExt_InCEPkts{instance=~\"$node..*\"}[5m])",
     "legendFormat": "InCEPkts"
    },
    {
     "expr": "irate(node_netstat_IpExt_InECT0Pkts{instance=~\"$node..*\"}[5m])",
     "legendFormat": "InECT0Pkts"
    },
    {
     "expr": "irate(node_netstat_IpExt_InECT1Pkts{instance=~\"$node..*\"}[5m])",
     "legendFormat": "InECT1Pkt"
    },
    {
     "expr": "irate(node_netstat_IpExt_InOctets{instance=~\"$node..*\"}[5m])",
     "legendFormat": "InOctets"
    },
    {
     "expr": "irate(node_netstat_IpExt_OutOctets{instance=~\"$node..*\"}[5m])",
     "legendFormat": "OutOctets"
    },
    {
     "expr": "irate(node_netstat_IpExt_InNoECTPkts{instance=~\"$node..*\"}[5m])",
     "legendFormat": "InNoECTPkts"
    }
   ]
  },
  {
   "title": "Netstat IP Forwarding",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 301 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Ip_ForwDatagrams{instance=~\"$node..*\"}[5m])",
     "legendFormat": "ForwDatagrams"
    },
    {
     "expr": "irate(node_netstat_Ip_Forwarding{instance=~\"$node..*\"}[5m])",
     "legendFormat": "Forwarding"
    }
   ]
  },
  {
   "title": "Netstat IP Reasambled",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 309 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Ip_ReasmFails{instance=~\"$node..*\"}[5m])",
     "legendFormat": "ReasmFails"
    },
    {
     "expr": "irate(node_netstat_Ip_ReasmOKs{instance=~\"$node..*\"}[5m])",
     "legendFormat": "ReasmOKs"
    },
    {
     "expr": "irate(node_netstat_Ip_ReasmReqds{instance=~\"$node..*\"}[5m])",
     "legendFormat": "ReasmReqds"
    },
    {
     "expr": "irate(node_netstat_Ip_ReasmTimeout{instance=~\"$node..*\"}[5m])",
     "legendFormat": "ReasmTimeout"
    }
   ]
  },
  {
   "title": "Netstat IP Fragmented",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 309 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Ip_FragCreates{instance=~\"$node..*\"}[5m])",
     "legendFormat": "FragCreates"
    },
    {
     "expr": "irate(node_netstat_Ip_FragFails{instance=~\"$node..*\"}[5m])",
     "legendFormat": "FragFails"
    },
    {
     "expr": "irate(node_netstat_Ip_FragOKs{instance=~\"$node..*\"}[5m])",
     "legendFormat": "FragOKs"
    }
   ]
  },
  { "title": "Network Netstat TCP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 317 } },
  {
   "title": "TCP Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 318 },
   "yaxes": [
    { "format": "short", "label": "connections" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~\"$node.*\"}",
     "legendFormat": "CurrEstab - Number of TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT"
    },
    {
     "expr": "node_netstat_Tcp_MaxConn{instance=~\"$node.*\"}",
     "legendFormat": "MaxConn - Limit on the total number of TCP connections the entity can support (Dinamic is \"-1\")"
    }
   ]
  },
  {
   "title": "TCP Segments",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 327 },
   "yaxes": [
    { "format": "short", "label": "segments" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Tcp_InCsumErrors{instance=~\"$node.*\"}[5m])",
     "legendFormat": "InCsumErrors - "
    },
    {
     "expr": "irate(node_netstat_Tcp_InErrs{instance=~\"$node.*\"}[5m])",
     "legendFormat": "InErrs - Number of segments received in error (e.g., bad TCP checksums)"
    },
    {
     "expr": "irate(node_netstat_Tcp_InSegs{instance=~\"$node.*\"}[5m])",
     "legendFormat": "InSegs - Number of segments received, including those received in error. This count includes segments received on currently established connections"
    },
    {
     "expr": "irate(node_netstat_Tcp_OutRsts{instance=~\"$node.*\"}[5m])",
     "legendFormat": "OutRsts - Number of TCP segments sent containing the RST flag"
    },
    {
     "expr": "irate(node_netstat_Tcp_OutSegs{instance=~\"$node.*\"}[5m])",
     "legendFormat": "OutSegs - Number of segments sent, including those on current connections but excluding those containing only retransmitted octets"
    },
    {
     "expr": "irate(node_netstat_Tcp_RetransSegs{instance=~\"$node.*\"}[5m])",
     "legendFormat": "RetransSegs - Number of segments retransmitted - that is, the number of TCP segments transmitted containing one or more previously transmitted octets"
    }
   ]
  },
  {
   "title": "TCP Direct Transition",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 336 },
   "yaxes": [
    { "format": "none", "label": "connections" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Tcp_ActiveOpens{instance=~\"$node.*\"}[5m])",
     "legendFormat": "ActiveOpens - TCP connections that have made a direct transition to the SYN-SENT state from the CLOSED state"
    },
    {
     "expr": "irate(node_netstat_Tcp_AttemptFails{instance=~\"$node.*\"}[5m])",
     "legendFormat": "AttemptFails - TCP connections that have made a direct transition to the CLOSED state from either the SYN-SENT and SYN-RCVD"
    },
    {
     "expr": "irate(node_netstat_Tcp_EstabResets{instance=~\"$node.*\"}[5m])",
     "legendFormat": "EstabResets - TCP connections that have made a direct transition to the CLOSED state from either the ESTABLISHED state or the CLOSE-WAIT state"
    },
    {
     "expr": "irate(node_netstat_Tcp_PassiveOpens{instance=~\"$node.*\"}[5m])",
     "legendFormat": "PassiveOpens - TCP connections that have made a direct transition to the SYN-RCVD state from the LISTEN state"
    }
   ]
  },
  {
   "title": "TCP Retransmission",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 345 },
   "yaxes": [
    { "format": "ms", "label": "milliseconds" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_RtoMax{instance=~\"$node.*\"}",
     "legendFormat": "RtoMax - Maximum value permitted by a TCP implementation for the retransmission timeout, measured in milliseconds"
    },
    {
     "expr": "node_netstat_Tcp_RtoMin{instance=~\"$node.*\"}",
     "legendFormat": "RtoMin - Minimum value permitted by a TCP implementation for the retransmission timeout, measured in milliseconds"
    }
   ]
  },
  { "title": "Network Netstat TCP Linux MIPs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 354 } },
  {
   "title": "TCP Aborts / Timeouts",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 355 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_TcpExt_TCPAbortOnClose{instance=~\"$node.*\"}[5m])",
     "legendFormat": "TCPAbortOnClose - Connections aborted due to early user close"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPAbortOnData{instance=~\"$node.*\"}[5m])",
     "legendFormat": "TCPAbortOnData - Connections aborted due to unexpected data"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPAbortOnLinger{instance=~\"$node.*\"}[5m])",
     "legendFormat": "TCPAbortOnLinger - Connections aborted in lingered state after being closed"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPAbortOnMemory{instance=~\"$node.*\"}[5m])",
     "legendFormat": "TCPAbortOnMemory - Connections aborted before attached to a socket"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPAbortOnTimeout{instance=~\"$node.*\"}[5m])",
     "legendFormat": "TCPAbortOnTimeout - Connections aborted due timeout"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPAbortFailed{instance=~\"$node.*\"}[5m])",
     "legendFormat": "TCPAbortFailed - Connections that need to be aborted but the kernel can't do it"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPTimeouts{instance=~\"$node.*\"}[5m])",
     "legendFormat": "TCPTimeouts - TCP timeouts events"
    }
   ]
  },
  {
   "title": "TCP Delayed ACK",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 355 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_TcpExt_DelayedACKLocked{instance=~\"$node.*\"}[5m])",
     "legendFormat": "DelayedACKLocked - Delayed acks further delayed because of locked socket"
    },
    {
     "expr": "irate(node_netstat_TcpExt_DelayedACKLost{instance=~\"$node.*\"}[5m])",
     "legendFormat": "DelayedACKLost - Times quick ack mode was activated"
    },
    {
     "expr": "irate(node_netstat_TcpExt_DelayedACKs{instance=~\"$node.*\"}[5m])",
     "legendFormat": "DelayedACKs - Delayed acks sent"
    }
   ]
  },
  {
   "title": "TCP SynCookie",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 355 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_TcpExt_SyncookiesFailed{instance=~\"$node.*\"}[5m])",
     "legendFormat": "SyncookiesFailed - Invalid SYN cookies received"
    },
    {
     "expr": "irate(node_netstat_TcpExt_SyncookiesRecv{instance=~\"$node.*\"}[5m])",
     "legendFormat": "SyncookiesRecv - SYN cookies received"
    },
    {
     "expr": "irate(node_netstat_TcpExt_SyncookiesSent{instance=~\"$node.*\"}[5m])",
     "legendFormat": "SyncookiesSent - SYN cookies sent"
    }
   ]
  },
  {
   "title": "TCP LOSS",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 366 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_TcpExt_TCPLossFailures{instance=~\"$node.*\"}[5m])",
     "legendFormat": "TCPLossFailures - TCP data loss events"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPLossProbeRecovery{instance=~\"$node.*\"}[5m])",
     "legendFormat": "TCPLossProbeRecovery -"
    }
   ]
  },
  {
   "title": "TCP DROPS",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 366 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_TcpExt_ListenDrops{instance=~\"$node.*\"}[5m])",
     "legendFormat": "ListenDrops - SYNs to LISTEN sockets ignored"
    },
    {
     "expr": "irate(node_netstat_TcpExt_LockDroppedIcmps{instance=~\"$node.*\"}[5m])",
     "legendFormat": "LockDroppedIcmps - ICMP packets dropped because socket was locked"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPDeferAcceptDrop{instance=~\"$node.*\"}[5m])",
     "legendFormat": "TCPDeferAcceptDrop -"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPBacklogDrop{instance=~\"$node.*\"}[5m])",
     "legendFormat": "TCPBacklogDrop - Packets dropped bacause the socket's receive queue was full"
    },
    {
     "expr": "irate(node_netstat_TcpExt_OutOfWindowIcmps{instance=~\"$node.*\"}[5m])",
     "legendFormat": "OutOfWindowIcmps - ICMP pkts dropped because they were out-of-window"
    }
   ]
  },
  {
   "title": "TCP Retrans",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 366 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_TcpExt_TCPForwardRetrans{instance=~\"$node.*\"}[5m])",
     "legendFormat": "TCPForwardRetrans - Packets losts retransmitted with Forward RTO-Recovery"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPSlowStartRetrans{instance=~\"$node.*\"}[5m])",
     "legendFormat": "TCPSlowStartRetrans - Packets losts retransmitted after a slow start"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPSynRetrans{instance=~\"$node.*\"}[5m])",
     "legendFormat": "TCPSynRetrans -"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPSpuriousRTOs{instance=~\"$node.*\"}[5m])",
     "legendFormat": "TCPSpuriousRTOs -"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPSpuriousRtxHostQueues{instance=~\"$node.*\"}[5m])",
     "legendFormat": "TCPSpuriousRtxHostQueues -"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPFullUndo{instance=~\"$node.*\"}[5m])",
     "legendFormat": "TCPFullUndo - Retransmits that undid the CWND reduction"
    }
   ]
  },
  {
   "title": "TCP Pruned",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 377 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_TcpExt_PruneCalled{instance=~\"$node.*\"}[5m])",
     "legendFormat": "PruneCalled - Pkts pruned from recv queue because of soc buf overrun"
    },
    {
     "expr": "irate(node_netstat_TcpExt_RcvPruned{instance=~\"$node.*\"}[5m])",
     "legendFormat": "RcvPruned - Packets pruned from receive queue"
    },
    {
     "expr": "irate(node_netstat_TcpExt_OfoPruned{instance=~\"$node.*\"}[5m])",
     "legendFormat": "OfoPruned - Packets dropped from out-of-order queue because of socket buffer overrun"
    }
   ]
  },
  {
   "title": "TCP Direct Copy",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 377 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_TcpExt_TCPDirectCopyFromBacklog{instance=~\"$node.*\"}[5m])",
     "legendFormat": "TCPDirectCopyFromBacklog - Packets directly received from backlog"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPDirectCopyFromPrequeue{instance=~\"$node.*\"}[5m])",
     "legendFormat": "TCPDirectCopyFromPrequeue - Packets directly received from prequeue"
    }
   ]
  },
  {
   "title": "TCP TimeWait",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 377 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_TcpExt_TW{instance=~\"$node.*\"}[5m])",
     "legendFormat": "TW - TCP sockets finished time wait in fast timer"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TWKilled{instance=~\"$node.*\"}[5m])",
     "legendFormat": "TWKilled - TCP sockets finished time wait in slow timer"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TWRecycled{instance=~\"$node.*\"}[5m])",
     "legendFormat": "TWRecycled - Time wait sockets recycled by time stamp"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPTimeWaitOverflow{instance=~\"$node.*\"}[5m])",
     "legendFormat": "TCPTimeWaitOverflow -"
    }
   ]
  },
  {
   "title": "TCP PAWS",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 388 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_TcpExt_PAWSActive{instance=~\"$node.*\"}[5m])",
     "legendFormat": "PAWSActive - Active connections rejected because of time stamp"
    },
    {
     "expr": "irate(node_netstat_TcpExt_PAWSEstab{instance=~\"$node.*\"}[5m])",
     "legendFormat": "PAWSEstab - Pkts rejects in estab connections because of timestamp"
    },
    {
     "expr": "irate(node_netstat_TcpExt_PAWSPassive{instance=~\"$node.*\"}[5m])",
     "legendFormat": "PAWSPassive - Passive connections rejected because of time stamp"
    }
   ]
  },
  {
   "title": "TCP DSACK",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 388 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_TcpExt_TCPDSACKIgnoredOld{instance=~\"$node.*\"}[5m])",
     "legendFormat": "TCPDSACKIgnoredOld - Discarded packets with duplicate SACK while retransmitting"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPDSACKOfoRecv{instance=~\"$node.*\"}[5m])",
     "legendFormat": "TCPDSACKOfoRecv -"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPDSACKOfoSent{instance=~\"$node.*\"}[5m])",
     "legendFormat": "TCPDSACKOfoSent -"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPDSACKOldSent{instance=~\"$node.*\"}[5m])",
     "legendFormat": "TCPDSACKOldSent - DSACKs sent for old packets"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPDSACKRecv{instance=~\"$node.*\"}[5m])",
     "legendFormat": "TCPDSACKRecv -"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPDSACKUndo{instance=~\"$node.*\"}[5m])",
     "legendFormat": "TCPDSACKUndo - Discarded packets with erroneous retransmit"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPDSACKIgnoredNoUndo{instance=~\"$node.*\"}[5m])",
     "legendFormat": "TCPDSACKIgnoredNoUndo - Discarded packets with duplicate SACK"
    }
   ]
  },
  {
   "title": "TCP SACK",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 388 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_TcpExt_TCPSackRecovery{instance=~\"$node.*\"}[5m])",
     "legendFormat": "TCPSackRecovery - Packets lost and recovered using selective ACK"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPSackRecoveryFail{instance=~\"$node.*\"}[5m])",
     "legendFormat": "TCPSackRecoveryFail - Issue while recovering packets lost using selective ACK"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPSackShiftFallback{instance=~\"$node.*\"}[5m])",
     "legendFormat": "TCPSackShiftFallback -"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPSackShifted{instance=~\"$node.*\"}[5m])",
     "legendFormat": "TCPSackShifted -"
    }
   ]
  },
  {
   "title": "TCP FastOpen / FastRetrans",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 399 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_TcpExt_TCPFastOpenActive{instance=~\"$node.*\"}[5m])",
     "legendFormat": "TCPFastOpenActive -"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPFastOpenActiveFail{instance=~\"$node.*\"}[5m])",
     "legendFormat": "TCPFastOpenActiveFail -"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPFastOpenCookieReqd{instance=~\"$node.*\"}[5m])",
     "legendFormat": "TCPFastOpenCookieReqd -"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPFastOpenListenOverflow{instance=~\"$node.*\"}[5m])",
     "legendFormat": "TCPFastOpenListenOverflow -"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPFastOpenPassive{instance=~\"$node.*\"}[5m])",
     "legendFormat": "TCPFastOpenPassive -"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPFastOpenPassiveFail{instance=~\"$node.*\"}[5m])",
     "legendFormat": "TCPFastOpenPassiveFail -"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPFastRetrans{instance=~\"$node.*\"}[5m])",
     "legendFormat": "TCPFastRetrans - Packets lost fast-retransmitted"
    }
   ]
  },
  {
   "title": "TCP HP",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 399 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_TcpExt_TCPHPAcks{instance=~\"$node.*\"}[5m])",
     "legendFormat": "TCPHPAcks - Acknowledgments not containing data received"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPHPHits{instance=~\"$node.*\"}[5m])",
     "legendFormat": "TCPHPHits - Packets header predicted"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPHPHitsToUser{instance=~\"$node.*\"}[5m])",
     "legendFormat": "TCPHPHitsToUser - Packets header predicted and directly queued to user"
    }
   ]
  },
  {
   "title": "TCP ZeroWindow",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 399 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_TcpExt_TCPToZeroWindowAdv{instance=~\"$node.*\"}[5m])",
     "legendFormat": "TCPToZeroWindowAdv -"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPWantZeroWindowAdv{instance=~\"$node.*\"}[5m])",
     "legendFormat": "TCPWantZeroWindowAdv -"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPFromZeroWindowAdv{instance=~\"$node.*\"}[5m])",
     "legendFormat": "TCPFromZeroWindowAdv -"
    }
   ]
  },
  {
   "title": "TCP Reorder",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 410 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_TcpExt_TCPFACKReorder{instance=~\"$node.*\"}[5m])",
     "legendFormat": "TCPFACKReorder - Detected packets with re-ordering using FACK"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPTSReorder{instance=~\"$node.*\"}[5m])",
     "legendFormat": "TCPTSReorder - Detected packets with re-ordering using timestamp option"
    }
   ]
  },
  {
   "title": "TCP etc 1",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 410 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_TcpExt_ArpFilter{instance=~\"$node.*\"}[5m])",
     "legendFormat": "ArpFilter - "
    },
    {
     "expr": "irate(node_netstat_TcpExt_BusyPollRxPackets{instance=~\"$node.*\"}[5m])",
     "legendFormat": "BusyPollRxPackets - "
    },
    {
     "expr": "irate(node_netstat_TcpExt_EmbryonicRsts{instance=~\"$node.*\"}[5m])",
     "legendFormat": "EmbryonicRsts - Resets received for embryonic SYN_RECV sockets"
    },
    {
     "expr": "irate(node_netstat_TcpExt_IPReversePathFilter{instance=~\"$node.*\"}[5m])",
     "legendFormat": "IPReversePathFilter -"
    },
    {
     "expr": "irate(node_netstat_TcpExt_ListenOverflows{instance=~\"$node.*\"}[5m])",
     "legendFormat": "ListenOverflows - Times the listen queue of a socket overflowed"
    }
   ]
  },
  {
   "title": "TCP etc 2",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 410 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_TcpExt_TCPSchedulerFailed{instance=~\"$node.*\"}[5m])",
     "legendFormat": "TCPSchedulerFailed -"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPAutoCorking{instance=~\"$node.*\"}[5m])",
     "legendFormat": "TCPAutoCorking -"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPChallengeACK{instance=~\"$node.*\"}[5m])",
     "legendFormat": "TCPChallengeACK -"
    }
   ]
  },
  { "title": "Network Netstat UDP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 421 } },
  {
   "title": "UDP In/Out",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 422 },
   "yaxes": [
    { "format": "short", "label": "datagrams" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Udp_InDatagrams{instance=~\"$node.*\"}[5m])",
     "legendFormat": "InDatagrams - Datagrams received"
    },
    {
     "expr": "irate(node_netstat_Udp_OutDatagrams{instance=~\"$node.*\"}[5m])",
     "legendFormat": "OutDatagrams - Datagrams sent"
    }
   ]
  },
  {
   "title": "UDP Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 431 },
   "yaxes": [
    { "format": "short", "label": "datagrams" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Udp_InCsumErrors{instance=~\"$node.*\"}[5m])",
     "legendFormat": "InCsumErrors - Datagrams with checksum errors"
    },
    {
     "expr": "irate(node_netstat_Udp_InErrors{instance=~\"$node.*\"}[5m])",
     "legendFormat": "InErrors - Datagrams that could not be delivered to an application"
    },
    {
     "expr": "irate(node_netstat_Udp_RcvbufErrors{instance=~\"$node.*\"}[5m])",
     "legendFormat": "RcvbufErrors - Datagrams for which not enough socket buffer memory to receive"
    },
    {
     "expr": "irate(node_netstat_Udp_SndbufErrors{instance=~\"$node.*\"}[5m])",
     "legendFormat": "SndbufErrors - Datagrams for which not enough socket buffer memory to transmit"
    },
    {
     "expr": "irate(node_netstat_Udp_NoPorts{instance=~\"$node.*\"}[5m])",
     "legendFormat": "NoPorts - Datagrams received on a port with no listener"
    }
   ]
  },
  {
   "title": "UDP Lite In/Out",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 440 },
   "yaxes": [
    { "format": "short", "label": "datagrams" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_UdpLite_InDatagrams{instance=~\"$node.*\"}[5m])",
     "legendFormat": "InDatagrams - Packets received"
    },
    {
     "expr": "irate(node_netstat_UdpLite_OutDatagrams{instance=~\"$node.*\"}[5m])",
     "legendFormat": "OutDatagrams - Packets sent"
    }
   ]
  },
  {
   "title": "UDP Lite Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 449 },
   "yaxes": [
    { "format": "short", "label": "datagrams" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_UdpLite_InCsumErrors{instance=~\"$node.*\"}[5m])",
     "legendFormat": "InCsumErrors - Datagrams with checksum errors"
    },
    {
     "expr": "irate(node_netstat_UdpLite_InErrors{instance=~\"$node.*\"}[5m])",
     "legendFormat": "InErrors - Datagrams that could not be delivered to an application"
    },
    {
     "expr": "irate(node_netstat_UdpLite_RcvbufErrors{instance=~\"$node.*\"}[5m])",
     "legendFormat": "RcvbufErrors - Datagrams for which not enough socket buffer memory to receive"
    },
    {
     "expr": "irate(node_netstat_UdpLite_SndbufErrors{instance=~\"$node.*\"}[5m])",
     "legendFormat": "SndbufErrors - Datagrams for which not enough socket buffer memory to transmit"
    },
    {
     "expr": "irate(node_netstat_UdpLite_NoPorts{instance=~\"$node.*\"}[5m])",
     "legendFormat": "NoPorts - Datagrams received on a port with no listener"
    }
   ]
  },
  { "title": "Network Netstat ICMP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 458 } },
  {
   "title": "ICMP In/Out - Messages / Redirects",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 459 },
   "yaxes": [
    { "format": "short", "label": "messages" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Icmp_InMsgs{instance=~\"$node.*\"}[5m])",
     "legendFormat": "InMsgs -  Messages which the entity received. Note that this counter includes all those counted by icmpInErrors"
    },
    {
     "expr": "irate(node_netstat_Icmp_InRedirects{instance=~\"$node.*\"}[5m])",
     "legendFormat": "InRedirects - Redirect messages received"
    },
    {
     "expr": "irate(node_netstat_Icmp_OutMsgs{instance=~\"$node.*\"}[5m])",
     "legendFormat": "OutMsgs - Messages which this entity attempted to send. Note that this counter includes all those counted by icmpOutErrors"
    },
    {
     "expr": "irate(node_netstat_Icmp_OutRedirects{instance=~\"$node.*\"}[5m])",
     "legendFormat": "OutRedirects -  Redirect messages sent. For a host, this object will always be zero, since hosts do not send redirects"
    }
   ]
  },
  {
   "title": "ICMP Problems",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 468 },
   "yaxes": [
    { "format": "short", "label": "messages" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Icmp_InCsumErrors{instance=~\"$node.*\"}[5m])",
     "legendFormat": "InCsumErrors - Messages with ICMP checksum errors"
    },
    {
     "expr": "irate(node_netstat_Icmp_InErrors{instance=~\"$node.*\"}[5m])",
     "legendFormat": "InErrors - Messages which the entity received but determined as having ICMP-specific errors (bad ICMP checksums, bad length, etc.)"
    },
    {
     "expr": "irate(node_netstat_Icmp_OutErrors{instance=~\"$node.*\"}[5m])",
     "legendFormat": "OutErrors - Messages which this entity did not send due to problems discovered within ICMP, such as a lack of buffers"
    },
    {
     "expr": "irate(node_netstat_Icmp_InDestUnreachs{instance=~\"$node.*\"}[5m])",
     "legendFormat": "InDestUnreachs - Destination Unreachable messages received"
    },
    {
     "expr": "irate(node_netstat_Icmp_OutDestUnreachs{instance=~\"$node.*\"}[5m])",
     "legendFormat": "OutDestUnreachs - Destination Unreachable messages sent"
    },
    {
     "expr": "irate(node_netstat_Icmp_InTimeExcds{instance=~\"$node.*\"}[5m])",
     "legendFormat": "InTimeExcds - Time Exceeded messages received"
    },
    {
     "expr": "irate(node_netstat_Icmp_OutTimeExcds{instance=~\"$node.*\"}[5m])",
     "legendFormat": "OutTimeExcds - Time Exceeded messages sent"
    },
    {
     "expr": "irate(node_netstat_Icmp_InParmProbs{instance=~\"$node.*\"}[5m])",
     "legendFormat": "InParmProbs - Parameter Problem messages received"
    },
    {
     "expr": "irate(node_netstat_Icmp_OutParmProbs{instance=~\"$node.*\"}[5m])",
     "legendFormat": "OutParmProb - Parameter Problem messages sent"
    },
    {
     "expr": "irate(node_netstat_Icmp_InSrcQuenchs{instance=~\"$node.*\"}[5m])",
     "legendFormat": "InSrcQuenchs - Source Quench messages received"
    },
    {
     "expr": "irate(node_netstat_Icmp_OutSrcQuenchs{instance=~\"$node.*\"}[5m])",
     "legendFormat": "OutSrcQuenchs - Source Quench messages sent"
    },
    {
     "expr": "irate(node_netstat_IcmpMsg_InType3{instance=~\"$node.*\"}[5m])",
     "legendFormat": "InType3 - Destination unreachable"
    },
    {
     "expr": "irate(node_netstat_IcmpMsg_OutType3{instance=~\"$node.*\"}[5m])",
     "legendFormat": "OutType3 - Destination unreachable"
    }
   ]
  },
  {
   "title": "ICMP Echos",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 477 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Icmp_InEchoReps{instance=~\"$node.*\"}[5m])",
     "legendFormat": "InEchoReps - Echo Reply messages received"
    },
    {
     "expr": "irate(node_netstat_Icmp_InEchos{instance=~\"$node.*\"}[5m])",
     "legendFormat": "InEchos - Echo (request) messages received"
    },
    {
     "expr": "irate(node_netstat_Icmp_OutEchoReps{instance=~\"$node.*\"}[5m])",
     "legendFormat": "OutEchoReps - Echo Reply messages sent"
    },
    {
     "expr": "irate(node_netstat_Icmp_OutEchos{instance=~\"$node.*\"}[5m])",
     "legendFormat": "OutEchos - Echo (request) messages sent"
    }
   ]
  },
  {
   "title": "ICMP Timestamps",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 477 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Icmp_InTimestampReps{instance=~\"$node.*\"}[5m])",
     "legendFormat": "InTimestampReps - Timestamp Reply messages received"
    },
    {
     "expr": "irate(node_netstat_Icmp_InTimestamps{instance=~\"$node.*\"}[5m])",
     "legendFormat": "InTimestamps - Timestamp (request) messages received"
    },
    {
     "expr": "irate(node_netstat_Icmp_OutTimestampReps{instance=~\"$node.*\"}[5m])",
     "legendFormat": "OutTimestampReps - Timestamp Reply messages sent"
    },
    {
     "expr": "irate(node_netstat_Icmp_OutTimestamps{instance=~\"$node.*\"}[5m])",
     "legendFormat": "OutTimestamps - Timestamp (request) messages sent"
    }
   ]
  },
  {
   "title": "ICMP Masks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 477 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Icmp_InAddrMaskReps{instance=~\"$node.*\"}[5m])",
     "legendFormat": "InAddrMaskReps - Address Mask Reply messages received"
    },
    {
     "expr": "irate(node_netstat_Icmp_InAddrMasks{instance=~\"$node.*\"}[5m])",
     "legendFormat": "InAddrMasks - Address Mask Request messages received"
    },
    {
     "expr": "irate(node_netstat_Icmp_OutAddrMaskReps{instance=~\"$node.*\"}[5m])",
     "legendFormat": "OutAddrMaskReps - Address Mask Reply messages sent"
    },
    {
     "expr": "irate(node_netstat_Icmp_OutAddrMasks{instance=~\"$node.*\"}[5m])",
     "legendFormat": "OutAddrMasks - Address Mask Request messages sent"
    }
   ]
  },
  {
   "title": "Node Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 486 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Exporter scrape time",
     "type": "graph",
     "description": "node_exporter: Duration of a scrape job.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 511 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(node_scrape_collector_duration_seconds)",
       "legendFormat": "{{collector}}"
      }
     ]
    }
   ]
  }
 ]
}