- name: Nginx firewall block CentOS
  block:

    - name: ensure firewalld started and enabled
      systemd:
        name: firewalld
        state: started
        enabled: yes

    - name: allow iotapm proxy port in firewall
      firewalld:
        port: "{{ iotapm_proxy_port }}/tcp"
        permanent: true
        state: enabled
        immediate: yes

    - name: allow iotapm proxy port via selinux seport
      seport:
        ports: "{{ iotapm_proxy_port }}"
        proto: tcp
        setype: http_port_t
        state: present

    - name: allow to revese proxy
      seboolean:
        name: httpd_can_network_connect
        state: yes
        persistent: yes

  when: ansible_distribution == 'CentOS'


- name: ufw block
  block:

    - name: allow iotapm proxy port in firewall
      ufw:
        rule: allow
        direction: in
        proto: tcp
        port: "{{ iotapm_proxy_port }}"

    - name: Set ufw logging
      ufw:
        logging: "{{ ufw_logging }}"

  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
